// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cwfgmFilter.proto

package ca.wise.grid.proto;

/**
 * Protobuf type {@code WISE.GridProto.CwfgmPolyReplaceGridFilter}
 */
public final class CwfgmPolyReplaceGridFilter extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WISE.GridProto.CwfgmPolyReplaceGridFilter)
    CwfgmPolyReplaceGridFilterOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CwfgmPolyReplaceGridFilter.newBuilder() to construct.
  private CwfgmPolyReplaceGridFilter(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CwfgmPolyReplaceGridFilter() {
    name_ = "";
    comments_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CwfgmPolyReplaceGridFilter();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CwfgmPolyReplaceGridFilter(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            version_ = input.readInt32();
            break;
          }
          case 18: {
            ca.hss.math.proto.GeoPoly.Builder subBuilder = null;
            if (shapeCase_ == 2) {
              subBuilder = ((ca.hss.math.proto.GeoPoly) shape_).toBuilder();
            }
            shape_ =
                input.readMessage(ca.hss.math.proto.GeoPoly.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ca.hss.math.proto.GeoPoly) shape_);
              shape_ = subBuilder.buildPartial();
            }
            shapeCase_ = 2;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            shapeCase_ = 3;
            shape_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            name_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000002;
            comments_ = s;
            break;
          }
          case 48: {
            bitField0_ |= 0x00000004;
            color_ = input.readUInt32();
            break;
          }
          case 56: {
            bitField0_ |= 0x00000008;
            size_ = input.readUInt64();
            break;
          }
          case 66: {
            ca.wise.grid.proto.CwfgmReplaceGridFilterBase.Builder subBuilder = null;
            if (filter_ != null) {
              subBuilder = filter_.toBuilder();
            }
            filter_ = input.readMessage(ca.wise.grid.proto.CwfgmReplaceGridFilterBase.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(filter_);
              filter_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.wise.grid.proto.CwfgmFilter.internal_static_WISE_GridProto_CwfgmPolyReplaceGridFilter_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.wise.grid.proto.CwfgmFilter.internal_static_WISE_GridProto_CwfgmPolyReplaceGridFilter_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.wise.grid.proto.CwfgmPolyReplaceGridFilter.class, ca.wise.grid.proto.CwfgmPolyReplaceGridFilter.Builder.class);
  }

  private int bitField0_;
  private int shapeCase_ = 0;
  private java.lang.Object shape_;
  public enum ShapeCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    POLYGONS(2),
    FILENAME(3),
    SHAPE_NOT_SET(0);
    private final int value;
    private ShapeCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ShapeCase valueOf(int value) {
      return forNumber(value);
    }

    public static ShapeCase forNumber(int value) {
      switch (value) {
        case 2: return POLYGONS;
        case 3: return FILENAME;
        case 0: return SHAPE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ShapeCase
  getShapeCase() {
    return ShapeCase.forNumber(
        shapeCase_);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int POLYGONS_FIELD_NUMBER = 2;
  /**
   * <code>.Geography.GeoPoly polygons = 2;</code>
   * @return Whether the polygons field is set.
   */
  @java.lang.Override
  public boolean hasPolygons() {
    return shapeCase_ == 2;
  }
  /**
   * <code>.Geography.GeoPoly polygons = 2;</code>
   * @return The polygons.
   */
  @java.lang.Override
  public ca.hss.math.proto.GeoPoly getPolygons() {
    if (shapeCase_ == 2) {
       return (ca.hss.math.proto.GeoPoly) shape_;
    }
    return ca.hss.math.proto.GeoPoly.getDefaultInstance();
  }
  /**
   * <code>.Geography.GeoPoly polygons = 2;</code>
   */
  @java.lang.Override
  public ca.hss.math.proto.GeoPolyOrBuilder getPolygonsOrBuilder() {
    if (shapeCase_ == 2) {
       return (ca.hss.math.proto.GeoPoly) shape_;
    }
    return ca.hss.math.proto.GeoPoly.getDefaultInstance();
  }

  public static final int FILENAME_FIELD_NUMBER = 3;
  /**
   * <code>string filename = 3;</code>
   * @return The filename.
   */
  public java.lang.String getFilename() {
    java.lang.Object ref = "";
    if (shapeCase_ == 3) {
      ref = shape_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (shapeCase_ == 3) {
        shape_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string filename = 3;</code>
   * @return The bytes for filename.
   */
  public com.google.protobuf.ByteString
      getFilenameBytes() {
    java.lang.Object ref = "";
    if (shapeCase_ == 3) {
      ref = shape_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (shapeCase_ == 3) {
        shape_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 4;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 4;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 4;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMENTS_FIELD_NUMBER = 5;
  private volatile java.lang.Object comments_;
  /**
   * <code>string comments = 5;</code>
   * @return Whether the comments field is set.
   */
  @java.lang.Override
  public boolean hasComments() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>string comments = 5;</code>
   * @return The comments.
   */
  @java.lang.Override
  public java.lang.String getComments() {
    java.lang.Object ref = comments_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      comments_ = s;
      return s;
    }
  }
  /**
   * <code>string comments = 5;</code>
   * @return The bytes for comments.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCommentsBytes() {
    java.lang.Object ref = comments_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      comments_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COLOR_FIELD_NUMBER = 6;
  private int color_;
  /**
   * <code>uint32 color = 6;</code>
   * @return Whether the color field is set.
   */
  @java.lang.Override
  public boolean hasColor() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>uint32 color = 6;</code>
   * @return The color.
   */
  @java.lang.Override
  public int getColor() {
    return color_;
  }

  public static final int SIZE_FIELD_NUMBER = 7;
  private long size_;
  /**
   * <code>uint64 size = 7;</code>
   * @return Whether the size field is set.
   */
  @java.lang.Override
  public boolean hasSize() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>uint64 size = 7;</code>
   * @return The size.
   */
  @java.lang.Override
  public long getSize() {
    return size_;
  }

  public static final int FILTER_FIELD_NUMBER = 8;
  private ca.wise.grid.proto.CwfgmReplaceGridFilterBase filter_;
  /**
   * <code>.WISE.GridProto.CwfgmReplaceGridFilterBase filter = 8;</code>
   * @return Whether the filter field is set.
   */
  @java.lang.Override
  public boolean hasFilter() {
    return filter_ != null;
  }
  /**
   * <code>.WISE.GridProto.CwfgmReplaceGridFilterBase filter = 8;</code>
   * @return The filter.
   */
  @java.lang.Override
  public ca.wise.grid.proto.CwfgmReplaceGridFilterBase getFilter() {
    return filter_ == null ? ca.wise.grid.proto.CwfgmReplaceGridFilterBase.getDefaultInstance() : filter_;
  }
  /**
   * <code>.WISE.GridProto.CwfgmReplaceGridFilterBase filter = 8;</code>
   */
  @java.lang.Override
  public ca.wise.grid.proto.CwfgmReplaceGridFilterBaseOrBuilder getFilterOrBuilder() {
    return getFilter();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0) {
      output.writeInt32(1, version_);
    }
    if (shapeCase_ == 2) {
      output.writeMessage(2, (ca.hss.math.proto.GeoPoly) shape_);
    }
    if (shapeCase_ == 3) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, shape_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, name_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, comments_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeUInt32(6, color_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeUInt64(7, size_);
    }
    if (filter_ != null) {
      output.writeMessage(8, getFilter());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, version_);
    }
    if (shapeCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (ca.hss.math.proto.GeoPoly) shape_);
    }
    if (shapeCase_ == 3) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, shape_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, name_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, comments_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, color_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(7, size_);
    }
    if (filter_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getFilter());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.wise.grid.proto.CwfgmPolyReplaceGridFilter)) {
      return super.equals(obj);
    }
    ca.wise.grid.proto.CwfgmPolyReplaceGridFilter other = (ca.wise.grid.proto.CwfgmPolyReplaceGridFilter) obj;

    if (getVersion()
        != other.getVersion()) return false;
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasComments() != other.hasComments()) return false;
    if (hasComments()) {
      if (!getComments()
          .equals(other.getComments())) return false;
    }
    if (hasColor() != other.hasColor()) return false;
    if (hasColor()) {
      if (getColor()
          != other.getColor()) return false;
    }
    if (hasSize() != other.hasSize()) return false;
    if (hasSize()) {
      if (getSize()
          != other.getSize()) return false;
    }
    if (hasFilter() != other.hasFilter()) return false;
    if (hasFilter()) {
      if (!getFilter()
          .equals(other.getFilter())) return false;
    }
    if (!getShapeCase().equals(other.getShapeCase())) return false;
    switch (shapeCase_) {
      case 2:
        if (!getPolygons()
            .equals(other.getPolygons())) return false;
        break;
      case 3:
        if (!getFilename()
            .equals(other.getFilename())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasComments()) {
      hash = (37 * hash) + COMMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getComments().hashCode();
    }
    if (hasColor()) {
      hash = (37 * hash) + COLOR_FIELD_NUMBER;
      hash = (53 * hash) + getColor();
    }
    if (hasSize()) {
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSize());
    }
    if (hasFilter()) {
      hash = (37 * hash) + FILTER_FIELD_NUMBER;
      hash = (53 * hash) + getFilter().hashCode();
    }
    switch (shapeCase_) {
      case 2:
        hash = (37 * hash) + POLYGONS_FIELD_NUMBER;
        hash = (53 * hash) + getPolygons().hashCode();
        break;
      case 3:
        hash = (37 * hash) + FILENAME_FIELD_NUMBER;
        hash = (53 * hash) + getFilename().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.wise.grid.proto.CwfgmPolyReplaceGridFilter parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.grid.proto.CwfgmPolyReplaceGridFilter parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.grid.proto.CwfgmPolyReplaceGridFilter parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.grid.proto.CwfgmPolyReplaceGridFilter parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.grid.proto.CwfgmPolyReplaceGridFilter parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.grid.proto.CwfgmPolyReplaceGridFilter parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.grid.proto.CwfgmPolyReplaceGridFilter parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.grid.proto.CwfgmPolyReplaceGridFilter parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.grid.proto.CwfgmPolyReplaceGridFilter parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.wise.grid.proto.CwfgmPolyReplaceGridFilter parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.grid.proto.CwfgmPolyReplaceGridFilter parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.grid.proto.CwfgmPolyReplaceGridFilter parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.wise.grid.proto.CwfgmPolyReplaceGridFilter prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WISE.GridProto.CwfgmPolyReplaceGridFilter}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WISE.GridProto.CwfgmPolyReplaceGridFilter)
      ca.wise.grid.proto.CwfgmPolyReplaceGridFilterOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.grid.proto.CwfgmFilter.internal_static_WISE_GridProto_CwfgmPolyReplaceGridFilter_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.grid.proto.CwfgmFilter.internal_static_WISE_GridProto_CwfgmPolyReplaceGridFilter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.grid.proto.CwfgmPolyReplaceGridFilter.class, ca.wise.grid.proto.CwfgmPolyReplaceGridFilter.Builder.class);
    }

    // Construct using ca.wise.grid.proto.CwfgmPolyReplaceGridFilter.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = 0;

      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      comments_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      color_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      size_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000008);
      if (filterBuilder_ == null) {
        filter_ = null;
      } else {
        filter_ = null;
        filterBuilder_ = null;
      }
      shapeCase_ = 0;
      shape_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.wise.grid.proto.CwfgmFilter.internal_static_WISE_GridProto_CwfgmPolyReplaceGridFilter_descriptor;
    }

    @java.lang.Override
    public ca.wise.grid.proto.CwfgmPolyReplaceGridFilter getDefaultInstanceForType() {
      return ca.wise.grid.proto.CwfgmPolyReplaceGridFilter.getDefaultInstance();
    }

    @java.lang.Override
    public ca.wise.grid.proto.CwfgmPolyReplaceGridFilter build() {
      ca.wise.grid.proto.CwfgmPolyReplaceGridFilter result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.wise.grid.proto.CwfgmPolyReplaceGridFilter buildPartial() {
      ca.wise.grid.proto.CwfgmPolyReplaceGridFilter result = new ca.wise.grid.proto.CwfgmPolyReplaceGridFilter(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.version_ = version_;
      if (shapeCase_ == 2) {
        if (polygonsBuilder_ == null) {
          result.shape_ = shape_;
        } else {
          result.shape_ = polygonsBuilder_.build();
        }
      }
      if (shapeCase_ == 3) {
        result.shape_ = shape_;
      }
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.comments_ = comments_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.color_ = color_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.size_ = size_;
        to_bitField0_ |= 0x00000008;
      }
      if (filterBuilder_ == null) {
        result.filter_ = filter_;
      } else {
        result.filter_ = filterBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      result.shapeCase_ = shapeCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.wise.grid.proto.CwfgmPolyReplaceGridFilter) {
        return mergeFrom((ca.wise.grid.proto.CwfgmPolyReplaceGridFilter)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.wise.grid.proto.CwfgmPolyReplaceGridFilter other) {
      if (other == ca.wise.grid.proto.CwfgmPolyReplaceGridFilter.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (other.hasName()) {
        bitField0_ |= 0x00000001;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasComments()) {
        bitField0_ |= 0x00000002;
        comments_ = other.comments_;
        onChanged();
      }
      if (other.hasColor()) {
        setColor(other.getColor());
      }
      if (other.hasSize()) {
        setSize(other.getSize());
      }
      if (other.hasFilter()) {
        mergeFilter(other.getFilter());
      }
      switch (other.getShapeCase()) {
        case POLYGONS: {
          mergePolygons(other.getPolygons());
          break;
        }
        case FILENAME: {
          shapeCase_ = 3;
          shape_ = other.shape_;
          onChanged();
          break;
        }
        case SHAPE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.wise.grid.proto.CwfgmPolyReplaceGridFilter parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.wise.grid.proto.CwfgmPolyReplaceGridFilter) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int shapeCase_ = 0;
    private java.lang.Object shape_;
    public ShapeCase
        getShapeCase() {
      return ShapeCase.forNumber(
          shapeCase_);
    }

    public Builder clearShape() {
      shapeCase_ = 0;
      shape_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private int version_ ;
    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <code>int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.GeoPoly, ca.hss.math.proto.GeoPoly.Builder, ca.hss.math.proto.GeoPolyOrBuilder> polygonsBuilder_;
    /**
     * <code>.Geography.GeoPoly polygons = 2;</code>
     * @return Whether the polygons field is set.
     */
    @java.lang.Override
    public boolean hasPolygons() {
      return shapeCase_ == 2;
    }
    /**
     * <code>.Geography.GeoPoly polygons = 2;</code>
     * @return The polygons.
     */
    @java.lang.Override
    public ca.hss.math.proto.GeoPoly getPolygons() {
      if (polygonsBuilder_ == null) {
        if (shapeCase_ == 2) {
          return (ca.hss.math.proto.GeoPoly) shape_;
        }
        return ca.hss.math.proto.GeoPoly.getDefaultInstance();
      } else {
        if (shapeCase_ == 2) {
          return polygonsBuilder_.getMessage();
        }
        return ca.hss.math.proto.GeoPoly.getDefaultInstance();
      }
    }
    /**
     * <code>.Geography.GeoPoly polygons = 2;</code>
     */
    public Builder setPolygons(ca.hss.math.proto.GeoPoly value) {
      if (polygonsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        shape_ = value;
        onChanged();
      } else {
        polygonsBuilder_.setMessage(value);
      }
      shapeCase_ = 2;
      return this;
    }
    /**
     * <code>.Geography.GeoPoly polygons = 2;</code>
     */
    public Builder setPolygons(
        ca.hss.math.proto.GeoPoly.Builder builderForValue) {
      if (polygonsBuilder_ == null) {
        shape_ = builderForValue.build();
        onChanged();
      } else {
        polygonsBuilder_.setMessage(builderForValue.build());
      }
      shapeCase_ = 2;
      return this;
    }
    /**
     * <code>.Geography.GeoPoly polygons = 2;</code>
     */
    public Builder mergePolygons(ca.hss.math.proto.GeoPoly value) {
      if (polygonsBuilder_ == null) {
        if (shapeCase_ == 2 &&
            shape_ != ca.hss.math.proto.GeoPoly.getDefaultInstance()) {
          shape_ = ca.hss.math.proto.GeoPoly.newBuilder((ca.hss.math.proto.GeoPoly) shape_)
              .mergeFrom(value).buildPartial();
        } else {
          shape_ = value;
        }
        onChanged();
      } else {
        if (shapeCase_ == 2) {
          polygonsBuilder_.mergeFrom(value);
        }
        polygonsBuilder_.setMessage(value);
      }
      shapeCase_ = 2;
      return this;
    }
    /**
     * <code>.Geography.GeoPoly polygons = 2;</code>
     */
    public Builder clearPolygons() {
      if (polygonsBuilder_ == null) {
        if (shapeCase_ == 2) {
          shapeCase_ = 0;
          shape_ = null;
          onChanged();
        }
      } else {
        if (shapeCase_ == 2) {
          shapeCase_ = 0;
          shape_ = null;
        }
        polygonsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.Geography.GeoPoly polygons = 2;</code>
     */
    public ca.hss.math.proto.GeoPoly.Builder getPolygonsBuilder() {
      return getPolygonsFieldBuilder().getBuilder();
    }
    /**
     * <code>.Geography.GeoPoly polygons = 2;</code>
     */
    @java.lang.Override
    public ca.hss.math.proto.GeoPolyOrBuilder getPolygonsOrBuilder() {
      if ((shapeCase_ == 2) && (polygonsBuilder_ != null)) {
        return polygonsBuilder_.getMessageOrBuilder();
      } else {
        if (shapeCase_ == 2) {
          return (ca.hss.math.proto.GeoPoly) shape_;
        }
        return ca.hss.math.proto.GeoPoly.getDefaultInstance();
      }
    }
    /**
     * <code>.Geography.GeoPoly polygons = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.GeoPoly, ca.hss.math.proto.GeoPoly.Builder, ca.hss.math.proto.GeoPolyOrBuilder> 
        getPolygonsFieldBuilder() {
      if (polygonsBuilder_ == null) {
        if (!(shapeCase_ == 2)) {
          shape_ = ca.hss.math.proto.GeoPoly.getDefaultInstance();
        }
        polygonsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.hss.math.proto.GeoPoly, ca.hss.math.proto.GeoPoly.Builder, ca.hss.math.proto.GeoPolyOrBuilder>(
                (ca.hss.math.proto.GeoPoly) shape_,
                getParentForChildren(),
                isClean());
        shape_ = null;
      }
      shapeCase_ = 2;
      onChanged();;
      return polygonsBuilder_;
    }

    /**
     * <code>string filename = 3;</code>
     * @return The filename.
     */
    @java.lang.Override
    public java.lang.String getFilename() {
      java.lang.Object ref = "";
      if (shapeCase_ == 3) {
        ref = shape_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (shapeCase_ == 3) {
          shape_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string filename = 3;</code>
     * @return The bytes for filename.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      java.lang.Object ref = "";
      if (shapeCase_ == 3) {
        ref = shape_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (shapeCase_ == 3) {
          shape_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string filename = 3;</code>
     * @param value The filename to set.
     * @return This builder for chaining.
     */
    public Builder setFilename(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  shapeCase_ = 3;
      shape_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string filename = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFilename() {
      if (shapeCase_ == 3) {
        shapeCase_ = 0;
        shape_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string filename = 3;</code>
     * @param value The bytes for filename to set.
     * @return This builder for chaining.
     */
    public Builder setFilenameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      shapeCase_ = 3;
      shape_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * not really optional but need to be able to suppress it in the old file format
     * </pre>
     *
     * <code>string name = 4;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * not really optional but need to be able to suppress it in the old file format
     * </pre>
     *
     * <code>string name = 4;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * not really optional but need to be able to suppress it in the old file format
     * </pre>
     *
     * <code>string name = 4;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * not really optional but need to be able to suppress it in the old file format
     * </pre>
     *
     * <code>string name = 4;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * not really optional but need to be able to suppress it in the old file format
     * </pre>
     *
     * <code>string name = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * not really optional but need to be able to suppress it in the old file format
     * </pre>
     *
     * <code>string name = 4;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object comments_ = "";
    /**
     * <code>string comments = 5;</code>
     * @return Whether the comments field is set.
     */
    public boolean hasComments() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>string comments = 5;</code>
     * @return The comments.
     */
    public java.lang.String getComments() {
      java.lang.Object ref = comments_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        comments_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string comments = 5;</code>
     * @return The bytes for comments.
     */
    public com.google.protobuf.ByteString
        getCommentsBytes() {
      java.lang.Object ref = comments_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        comments_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string comments = 5;</code>
     * @param value The comments to set.
     * @return This builder for chaining.
     */
    public Builder setComments(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      comments_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string comments = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearComments() {
      bitField0_ = (bitField0_ & ~0x00000002);
      comments_ = getDefaultInstance().getComments();
      onChanged();
      return this;
    }
    /**
     * <code>string comments = 5;</code>
     * @param value The bytes for comments to set.
     * @return This builder for chaining.
     */
    public Builder setCommentsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      comments_ = value;
      onChanged();
      return this;
    }

    private int color_ ;
    /**
     * <code>uint32 color = 6;</code>
     * @return Whether the color field is set.
     */
    @java.lang.Override
    public boolean hasColor() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>uint32 color = 6;</code>
     * @return The color.
     */
    @java.lang.Override
    public int getColor() {
      return color_;
    }
    /**
     * <code>uint32 color = 6;</code>
     * @param value The color to set.
     * @return This builder for chaining.
     */
    public Builder setColor(int value) {
      bitField0_ |= 0x00000004;
      color_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 color = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearColor() {
      bitField0_ = (bitField0_ & ~0x00000004);
      color_ = 0;
      onChanged();
      return this;
    }

    private long size_ ;
    /**
     * <code>uint64 size = 7;</code>
     * @return Whether the size field is set.
     */
    @java.lang.Override
    public boolean hasSize() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>uint64 size = 7;</code>
     * @return The size.
     */
    @java.lang.Override
    public long getSize() {
      return size_;
    }
    /**
     * <code>uint64 size = 7;</code>
     * @param value The size to set.
     * @return This builder for chaining.
     */
    public Builder setSize(long value) {
      bitField0_ |= 0x00000008;
      size_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 size = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSize() {
      bitField0_ = (bitField0_ & ~0x00000008);
      size_ = 0L;
      onChanged();
      return this;
    }

    private ca.wise.grid.proto.CwfgmReplaceGridFilterBase filter_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.grid.proto.CwfgmReplaceGridFilterBase, ca.wise.grid.proto.CwfgmReplaceGridFilterBase.Builder, ca.wise.grid.proto.CwfgmReplaceGridFilterBaseOrBuilder> filterBuilder_;
    /**
     * <code>.WISE.GridProto.CwfgmReplaceGridFilterBase filter = 8;</code>
     * @return Whether the filter field is set.
     */
    public boolean hasFilter() {
      return filterBuilder_ != null || filter_ != null;
    }
    /**
     * <code>.WISE.GridProto.CwfgmReplaceGridFilterBase filter = 8;</code>
     * @return The filter.
     */
    public ca.wise.grid.proto.CwfgmReplaceGridFilterBase getFilter() {
      if (filterBuilder_ == null) {
        return filter_ == null ? ca.wise.grid.proto.CwfgmReplaceGridFilterBase.getDefaultInstance() : filter_;
      } else {
        return filterBuilder_.getMessage();
      }
    }
    /**
     * <code>.WISE.GridProto.CwfgmReplaceGridFilterBase filter = 8;</code>
     */
    public Builder setFilter(ca.wise.grid.proto.CwfgmReplaceGridFilterBase value) {
      if (filterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        filter_ = value;
        onChanged();
      } else {
        filterBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.WISE.GridProto.CwfgmReplaceGridFilterBase filter = 8;</code>
     */
    public Builder setFilter(
        ca.wise.grid.proto.CwfgmReplaceGridFilterBase.Builder builderForValue) {
      if (filterBuilder_ == null) {
        filter_ = builderForValue.build();
        onChanged();
      } else {
        filterBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.WISE.GridProto.CwfgmReplaceGridFilterBase filter = 8;</code>
     */
    public Builder mergeFilter(ca.wise.grid.proto.CwfgmReplaceGridFilterBase value) {
      if (filterBuilder_ == null) {
        if (filter_ != null) {
          filter_ =
            ca.wise.grid.proto.CwfgmReplaceGridFilterBase.newBuilder(filter_).mergeFrom(value).buildPartial();
        } else {
          filter_ = value;
        }
        onChanged();
      } else {
        filterBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.WISE.GridProto.CwfgmReplaceGridFilterBase filter = 8;</code>
     */
    public Builder clearFilter() {
      if (filterBuilder_ == null) {
        filter_ = null;
        onChanged();
      } else {
        filter_ = null;
        filterBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.WISE.GridProto.CwfgmReplaceGridFilterBase filter = 8;</code>
     */
    public ca.wise.grid.proto.CwfgmReplaceGridFilterBase.Builder getFilterBuilder() {
      
      onChanged();
      return getFilterFieldBuilder().getBuilder();
    }
    /**
     * <code>.WISE.GridProto.CwfgmReplaceGridFilterBase filter = 8;</code>
     */
    public ca.wise.grid.proto.CwfgmReplaceGridFilterBaseOrBuilder getFilterOrBuilder() {
      if (filterBuilder_ != null) {
        return filterBuilder_.getMessageOrBuilder();
      } else {
        return filter_ == null ?
            ca.wise.grid.proto.CwfgmReplaceGridFilterBase.getDefaultInstance() : filter_;
      }
    }
    /**
     * <code>.WISE.GridProto.CwfgmReplaceGridFilterBase filter = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.grid.proto.CwfgmReplaceGridFilterBase, ca.wise.grid.proto.CwfgmReplaceGridFilterBase.Builder, ca.wise.grid.proto.CwfgmReplaceGridFilterBaseOrBuilder> 
        getFilterFieldBuilder() {
      if (filterBuilder_ == null) {
        filterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.grid.proto.CwfgmReplaceGridFilterBase, ca.wise.grid.proto.CwfgmReplaceGridFilterBase.Builder, ca.wise.grid.proto.CwfgmReplaceGridFilterBaseOrBuilder>(
                getFilter(),
                getParentForChildren(),
                isClean());
        filter_ = null;
      }
      return filterBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WISE.GridProto.CwfgmPolyReplaceGridFilter)
  }

  // @@protoc_insertion_point(class_scope:WISE.GridProto.CwfgmPolyReplaceGridFilter)
  private static final ca.wise.grid.proto.CwfgmPolyReplaceGridFilter DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.wise.grid.proto.CwfgmPolyReplaceGridFilter();
  }

  public static ca.wise.grid.proto.CwfgmPolyReplaceGridFilter getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CwfgmPolyReplaceGridFilter>
      PARSER = new com.google.protobuf.AbstractParser<CwfgmPolyReplaceGridFilter>() {
    @java.lang.Override
    public CwfgmPolyReplaceGridFilter parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CwfgmPolyReplaceGridFilter(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CwfgmPolyReplaceGridFilter> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CwfgmPolyReplaceGridFilter> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.wise.grid.proto.CwfgmPolyReplaceGridFilter getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

