// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cwfgmFilter.proto

package ca.wise.grid.proto;

public interface CwfgmTargetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.GridProto.CwfgmTarget)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>.Geography.GeoPoly targets = 2;</code>
   * @return Whether the targets field is set.
   */
  boolean hasTargets();
  /**
   * <code>.Geography.GeoPoly targets = 2;</code>
   * @return The targets.
   */
  ca.hss.math.proto.GeoPoly getTargets();
  /**
   * <code>.Geography.GeoPoly targets = 2;</code>
   */
  ca.hss.math.proto.GeoPolyOrBuilder getTargetsOrBuilder();

  /**
   * <code>string filename = 3;</code>
   * @return The filename.
   */
  java.lang.String getFilename();
  /**
   * <code>string filename = 3;</code>
   * @return The bytes for filename.
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 4;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 4;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 4;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string comments = 5;</code>
   * @return Whether the comments field is set.
   */
  boolean hasComments();
  /**
   * <code>string comments = 5;</code>
   * @return The comments.
   */
  java.lang.String getComments();
  /**
   * <code>string comments = 5;</code>
   * @return The bytes for comments.
   */
  com.google.protobuf.ByteString
      getCommentsBytes();

  /**
   * <code>uint32 color = 6;</code>
   * @return Whether the color field is set.
   */
  boolean hasColor();
  /**
   * <code>uint32 color = 6;</code>
   * @return The color.
   */
  int getColor();

  /**
   * <code>uint64 symbol = 7;</code>
   * @return Whether the symbol field is set.
   */
  boolean hasSymbol();
  /**
   * <code>uint64 symbol = 7;</code>
   * @return The symbol.
   */
  long getSymbol();

  /**
   * <code>sint32 displaySize = 8;</code>
   * @return Whether the displaySize field is set.
   */
  boolean hasDisplaySize();
  /**
   * <code>sint32 displaySize = 8;</code>
   * @return The displaySize.
   */
  int getDisplaySize();

  /**
   * <code>bool imported = 9;</code>
   * @return Whether the imported field is set.
   */
  boolean hasImported();
  /**
   * <code>bool imported = 9;</code>
   * @return The imported.
   */
  boolean getImported();

  public ca.wise.grid.proto.CwfgmTarget.DataCase getDataCase();
}
