// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cwfgmFilter.proto

package ca.wise.grid.proto;

public interface CwfgmVectorFilterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.GridProto.CwfgmVectorFilter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>.Math.Double fireBreakWidth = 2;</code>
   * @return Whether the fireBreakWidth field is set.
   */
  boolean hasFireBreakWidth();
  /**
   * <code>.Math.Double fireBreakWidth = 2;</code>
   * @return The fireBreakWidth.
   */
  ca.hss.math.proto.Double getFireBreakWidth();
  /**
   * <code>.Math.Double fireBreakWidth = 2;</code>
   */
  ca.hss.math.proto.DoubleOrBuilder getFireBreakWidthOrBuilder();

  /**
   * <code>.Geography.GeoPoly polygons = 3;</code>
   * @return Whether the polygons field is set.
   */
  boolean hasPolygons();
  /**
   * <code>.Geography.GeoPoly polygons = 3;</code>
   * @return The polygons.
   */
  ca.hss.math.proto.GeoPoly getPolygons();
  /**
   * <code>.Geography.GeoPoly polygons = 3;</code>
   */
  ca.hss.math.proto.GeoPolyOrBuilder getPolygonsOrBuilder();

  /**
   * <code>string filename = 4;</code>
   * @return The filename.
   */
  java.lang.String getFilename();
  /**
   * <code>string filename = 4;</code>
   * @return The bytes for filename.
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 5;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 5;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 5;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string comments = 6;</code>
   * @return Whether the comments field is set.
   */
  boolean hasComments();
  /**
   * <code>string comments = 6;</code>
   * @return The comments.
   */
  java.lang.String getComments();
  /**
   * <code>string comments = 6;</code>
   * @return The bytes for comments.
   */
  com.google.protobuf.ByteString
      getCommentsBytes();

  /**
   * <code>uint32 color = 7;</code>
   * @return Whether the color field is set.
   */
  boolean hasColor();
  /**
   * <code>uint32 color = 7;</code>
   * @return The color.
   */
  int getColor();

  /**
   * <code>uint32 fillColor = 8;</code>
   * @return Whether the fillColor field is set.
   */
  boolean hasFillColor();
  /**
   * <code>uint32 fillColor = 8;</code>
   * @return The fillColor.
   */
  int getFillColor();

  /**
   * <code>uint64 symbol = 9;</code>
   * @return Whether the symbol field is set.
   */
  boolean hasSymbol();
  /**
   * <code>uint64 symbol = 9;</code>
   * @return The symbol.
   */
  long getSymbol();

  /**
   * <code>sint32 width = 10;</code>
   * @return Whether the width field is set.
   */
  boolean hasWidth();
  /**
   * <code>sint32 width = 10;</code>
   * @return The width.
   */
  int getWidth();

  /**
   * <code>bool imported = 11;</code>
   * @return Whether the imported field is set.
   */
  boolean hasImported();
  /**
   * <code>bool imported = 11;</code>
   * @return The imported.
   */
  boolean getImported();

  public ca.wise.grid.proto.CwfgmVectorFilter.DataCase getDataCase();
}
