// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cwfgmFilter.proto

package ca.wise.grid.proto;

/**
 * Protobuf type {@code WISE.GridProto.CwfgmReplaceGridFilter}
 */
public final class CwfgmReplaceGridFilter extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WISE.GridProto.CwfgmReplaceGridFilter)
    CwfgmReplaceGridFilterOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CwfgmReplaceGridFilter.newBuilder() to construct.
  private CwfgmReplaceGridFilter(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CwfgmReplaceGridFilter() {
    name_ = "";
    comments_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CwfgmReplaceGridFilter();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CwfgmReplaceGridFilter(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            version_ = input.readInt32();
            break;
          }
          case 18: {
            ca.hss.math.proto.GeoPoint.Builder subBuilder = null;
            if (pointOne_ != null) {
              subBuilder = pointOne_.toBuilder();
            }
            pointOne_ = input.readMessage(ca.hss.math.proto.GeoPoint.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pointOne_);
              pointOne_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            ca.hss.math.proto.GeoPoint.Builder subBuilder = null;
            if (pointTwo_ != null) {
              subBuilder = pointTwo_.toBuilder();
            }
            pointTwo_ = input.readMessage(ca.hss.math.proto.GeoPoint.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pointTwo_);
              pointTwo_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            ca.hss.math.proto.Double.Builder subBuilder = null;
            if (xLLCorner_ != null) {
              subBuilder = xLLCorner_.toBuilder();
            }
            xLLCorner_ = input.readMessage(ca.hss.math.proto.Double.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(xLLCorner_);
              xLLCorner_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            ca.hss.math.proto.Double.Builder subBuilder = null;
            if (yLLCorner_ != null) {
              subBuilder = yLLCorner_.toBuilder();
            }
            yLLCorner_ = input.readMessage(ca.hss.math.proto.Double.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(yLLCorner_);
              yLLCorner_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            ca.hss.math.proto.Double.Builder subBuilder = null;
            if (resolution_ != null) {
              subBuilder = resolution_.toBuilder();
            }
            resolution_ = input.readMessage(ca.hss.math.proto.Double.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(resolution_);
              resolution_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            com.google.protobuf.BoolValue.Builder subBuilder = null;
            if (landscape_ != null) {
              subBuilder = landscape_.toBuilder();
            }
            landscape_ = input.readMessage(com.google.protobuf.BoolValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(landscape_);
              landscape_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            name_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000002;
            comments_ = s;
            break;
          }
          case 82: {
            ca.wise.grid.proto.CwfgmReplaceGridFilterBase.Builder subBuilder = null;
            if (filter_ != null) {
              subBuilder = filter_.toBuilder();
            }
            filter_ = input.readMessage(ca.wise.grid.proto.CwfgmReplaceGridFilterBase.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(filter_);
              filter_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.wise.grid.proto.CwfgmFilter.internal_static_WISE_GridProto_CwfgmReplaceGridFilter_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.wise.grid.proto.CwfgmFilter.internal_static_WISE_GridProto_CwfgmReplaceGridFilter_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.wise.grid.proto.CwfgmReplaceGridFilter.class, ca.wise.grid.proto.CwfgmReplaceGridFilter.Builder.class);
  }

  private int bitField0_;
  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int POINTONE_FIELD_NUMBER = 2;
  private ca.hss.math.proto.GeoPoint pointOne_;
  /**
   * <code>.Geography.GeoPoint pointOne = 2;</code>
   * @return Whether the pointOne field is set.
   */
  @java.lang.Override
  public boolean hasPointOne() {
    return pointOne_ != null;
  }
  /**
   * <code>.Geography.GeoPoint pointOne = 2;</code>
   * @return The pointOne.
   */
  @java.lang.Override
  public ca.hss.math.proto.GeoPoint getPointOne() {
    return pointOne_ == null ? ca.hss.math.proto.GeoPoint.getDefaultInstance() : pointOne_;
  }
  /**
   * <code>.Geography.GeoPoint pointOne = 2;</code>
   */
  @java.lang.Override
  public ca.hss.math.proto.GeoPointOrBuilder getPointOneOrBuilder() {
    return getPointOne();
  }

  public static final int POINTTWO_FIELD_NUMBER = 3;
  private ca.hss.math.proto.GeoPoint pointTwo_;
  /**
   * <code>.Geography.GeoPoint pointTwo = 3;</code>
   * @return Whether the pointTwo field is set.
   */
  @java.lang.Override
  public boolean hasPointTwo() {
    return pointTwo_ != null;
  }
  /**
   * <code>.Geography.GeoPoint pointTwo = 3;</code>
   * @return The pointTwo.
   */
  @java.lang.Override
  public ca.hss.math.proto.GeoPoint getPointTwo() {
    return pointTwo_ == null ? ca.hss.math.proto.GeoPoint.getDefaultInstance() : pointTwo_;
  }
  /**
   * <code>.Geography.GeoPoint pointTwo = 3;</code>
   */
  @java.lang.Override
  public ca.hss.math.proto.GeoPointOrBuilder getPointTwoOrBuilder() {
    return getPointTwo();
  }

  public static final int XLLCORNER_FIELD_NUMBER = 4;
  private ca.hss.math.proto.Double xLLCorner_;
  /**
   * <code>.Math.Double xLLCorner = 4;</code>
   * @return Whether the xLLCorner field is set.
   */
  @java.lang.Override
  public boolean hasXLLCorner() {
    return xLLCorner_ != null;
  }
  /**
   * <code>.Math.Double xLLCorner = 4;</code>
   * @return The xLLCorner.
   */
  @java.lang.Override
  public ca.hss.math.proto.Double getXLLCorner() {
    return xLLCorner_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : xLLCorner_;
  }
  /**
   * <code>.Math.Double xLLCorner = 4;</code>
   */
  @java.lang.Override
  public ca.hss.math.proto.DoubleOrBuilder getXLLCornerOrBuilder() {
    return getXLLCorner();
  }

  public static final int YLLCORNER_FIELD_NUMBER = 5;
  private ca.hss.math.proto.Double yLLCorner_;
  /**
   * <code>.Math.Double yLLCorner = 5;</code>
   * @return Whether the yLLCorner field is set.
   */
  @java.lang.Override
  public boolean hasYLLCorner() {
    return yLLCorner_ != null;
  }
  /**
   * <code>.Math.Double yLLCorner = 5;</code>
   * @return The yLLCorner.
   */
  @java.lang.Override
  public ca.hss.math.proto.Double getYLLCorner() {
    return yLLCorner_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : yLLCorner_;
  }
  /**
   * <code>.Math.Double yLLCorner = 5;</code>
   */
  @java.lang.Override
  public ca.hss.math.proto.DoubleOrBuilder getYLLCornerOrBuilder() {
    return getYLLCorner();
  }

  public static final int RESOLUTION_FIELD_NUMBER = 6;
  private ca.hss.math.proto.Double resolution_;
  /**
   * <code>.Math.Double resolution = 6;</code>
   * @return Whether the resolution field is set.
   */
  @java.lang.Override
  public boolean hasResolution() {
    return resolution_ != null;
  }
  /**
   * <code>.Math.Double resolution = 6;</code>
   * @return The resolution.
   */
  @java.lang.Override
  public ca.hss.math.proto.Double getResolution() {
    return resolution_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : resolution_;
  }
  /**
   * <code>.Math.Double resolution = 6;</code>
   */
  @java.lang.Override
  public ca.hss.math.proto.DoubleOrBuilder getResolutionOrBuilder() {
    return getResolution();
  }

  public static final int LANDSCAPE_FIELD_NUMBER = 7;
  private com.google.protobuf.BoolValue landscape_;
  /**
   * <code>.google.protobuf.BoolValue landscape = 7;</code>
   * @return Whether the landscape field is set.
   */
  @java.lang.Override
  public boolean hasLandscape() {
    return landscape_ != null;
  }
  /**
   * <code>.google.protobuf.BoolValue landscape = 7;</code>
   * @return The landscape.
   */
  @java.lang.Override
  public com.google.protobuf.BoolValue getLandscape() {
    return landscape_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : landscape_;
  }
  /**
   * <code>.google.protobuf.BoolValue landscape = 7;</code>
   */
  @java.lang.Override
  public com.google.protobuf.BoolValueOrBuilder getLandscapeOrBuilder() {
    return getLandscape();
  }

  public static final int NAME_FIELD_NUMBER = 8;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 8;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 8;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 8;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMENTS_FIELD_NUMBER = 9;
  private volatile java.lang.Object comments_;
  /**
   * <code>string comments = 9;</code>
   * @return Whether the comments field is set.
   */
  @java.lang.Override
  public boolean hasComments() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>string comments = 9;</code>
   * @return The comments.
   */
  @java.lang.Override
  public java.lang.String getComments() {
    java.lang.Object ref = comments_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      comments_ = s;
      return s;
    }
  }
  /**
   * <code>string comments = 9;</code>
   * @return The bytes for comments.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCommentsBytes() {
    java.lang.Object ref = comments_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      comments_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILTER_FIELD_NUMBER = 10;
  private ca.wise.grid.proto.CwfgmReplaceGridFilterBase filter_;
  /**
   * <code>.WISE.GridProto.CwfgmReplaceGridFilterBase filter = 10;</code>
   * @return Whether the filter field is set.
   */
  @java.lang.Override
  public boolean hasFilter() {
    return filter_ != null;
  }
  /**
   * <code>.WISE.GridProto.CwfgmReplaceGridFilterBase filter = 10;</code>
   * @return The filter.
   */
  @java.lang.Override
  public ca.wise.grid.proto.CwfgmReplaceGridFilterBase getFilter() {
    return filter_ == null ? ca.wise.grid.proto.CwfgmReplaceGridFilterBase.getDefaultInstance() : filter_;
  }
  /**
   * <code>.WISE.GridProto.CwfgmReplaceGridFilterBase filter = 10;</code>
   */
  @java.lang.Override
  public ca.wise.grid.proto.CwfgmReplaceGridFilterBaseOrBuilder getFilterOrBuilder() {
    return getFilter();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0) {
      output.writeInt32(1, version_);
    }
    if (pointOne_ != null) {
      output.writeMessage(2, getPointOne());
    }
    if (pointTwo_ != null) {
      output.writeMessage(3, getPointTwo());
    }
    if (xLLCorner_ != null) {
      output.writeMessage(4, getXLLCorner());
    }
    if (yLLCorner_ != null) {
      output.writeMessage(5, getYLLCorner());
    }
    if (resolution_ != null) {
      output.writeMessage(6, getResolution());
    }
    if (landscape_ != null) {
      output.writeMessage(7, getLandscape());
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, name_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, comments_);
    }
    if (filter_ != null) {
      output.writeMessage(10, getFilter());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, version_);
    }
    if (pointOne_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPointOne());
    }
    if (pointTwo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getPointTwo());
    }
    if (xLLCorner_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getXLLCorner());
    }
    if (yLLCorner_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getYLLCorner());
    }
    if (resolution_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getResolution());
    }
    if (landscape_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getLandscape());
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, name_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, comments_);
    }
    if (filter_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getFilter());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.wise.grid.proto.CwfgmReplaceGridFilter)) {
      return super.equals(obj);
    }
    ca.wise.grid.proto.CwfgmReplaceGridFilter other = (ca.wise.grid.proto.CwfgmReplaceGridFilter) obj;

    if (getVersion()
        != other.getVersion()) return false;
    if (hasPointOne() != other.hasPointOne()) return false;
    if (hasPointOne()) {
      if (!getPointOne()
          .equals(other.getPointOne())) return false;
    }
    if (hasPointTwo() != other.hasPointTwo()) return false;
    if (hasPointTwo()) {
      if (!getPointTwo()
          .equals(other.getPointTwo())) return false;
    }
    if (hasXLLCorner() != other.hasXLLCorner()) return false;
    if (hasXLLCorner()) {
      if (!getXLLCorner()
          .equals(other.getXLLCorner())) return false;
    }
    if (hasYLLCorner() != other.hasYLLCorner()) return false;
    if (hasYLLCorner()) {
      if (!getYLLCorner()
          .equals(other.getYLLCorner())) return false;
    }
    if (hasResolution() != other.hasResolution()) return false;
    if (hasResolution()) {
      if (!getResolution()
          .equals(other.getResolution())) return false;
    }
    if (hasLandscape() != other.hasLandscape()) return false;
    if (hasLandscape()) {
      if (!getLandscape()
          .equals(other.getLandscape())) return false;
    }
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasComments() != other.hasComments()) return false;
    if (hasComments()) {
      if (!getComments()
          .equals(other.getComments())) return false;
    }
    if (hasFilter() != other.hasFilter()) return false;
    if (hasFilter()) {
      if (!getFilter()
          .equals(other.getFilter())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    if (hasPointOne()) {
      hash = (37 * hash) + POINTONE_FIELD_NUMBER;
      hash = (53 * hash) + getPointOne().hashCode();
    }
    if (hasPointTwo()) {
      hash = (37 * hash) + POINTTWO_FIELD_NUMBER;
      hash = (53 * hash) + getPointTwo().hashCode();
    }
    if (hasXLLCorner()) {
      hash = (37 * hash) + XLLCORNER_FIELD_NUMBER;
      hash = (53 * hash) + getXLLCorner().hashCode();
    }
    if (hasYLLCorner()) {
      hash = (37 * hash) + YLLCORNER_FIELD_NUMBER;
      hash = (53 * hash) + getYLLCorner().hashCode();
    }
    if (hasResolution()) {
      hash = (37 * hash) + RESOLUTION_FIELD_NUMBER;
      hash = (53 * hash) + getResolution().hashCode();
    }
    if (hasLandscape()) {
      hash = (37 * hash) + LANDSCAPE_FIELD_NUMBER;
      hash = (53 * hash) + getLandscape().hashCode();
    }
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasComments()) {
      hash = (37 * hash) + COMMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getComments().hashCode();
    }
    if (hasFilter()) {
      hash = (37 * hash) + FILTER_FIELD_NUMBER;
      hash = (53 * hash) + getFilter().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.wise.grid.proto.CwfgmReplaceGridFilter parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.grid.proto.CwfgmReplaceGridFilter parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.grid.proto.CwfgmReplaceGridFilter parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.grid.proto.CwfgmReplaceGridFilter parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.grid.proto.CwfgmReplaceGridFilter parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.grid.proto.CwfgmReplaceGridFilter parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.grid.proto.CwfgmReplaceGridFilter parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.grid.proto.CwfgmReplaceGridFilter parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.grid.proto.CwfgmReplaceGridFilter parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.wise.grid.proto.CwfgmReplaceGridFilter parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.grid.proto.CwfgmReplaceGridFilter parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.grid.proto.CwfgmReplaceGridFilter parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.wise.grid.proto.CwfgmReplaceGridFilter prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WISE.GridProto.CwfgmReplaceGridFilter}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WISE.GridProto.CwfgmReplaceGridFilter)
      ca.wise.grid.proto.CwfgmReplaceGridFilterOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.grid.proto.CwfgmFilter.internal_static_WISE_GridProto_CwfgmReplaceGridFilter_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.grid.proto.CwfgmFilter.internal_static_WISE_GridProto_CwfgmReplaceGridFilter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.grid.proto.CwfgmReplaceGridFilter.class, ca.wise.grid.proto.CwfgmReplaceGridFilter.Builder.class);
    }

    // Construct using ca.wise.grid.proto.CwfgmReplaceGridFilter.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = 0;

      if (pointOneBuilder_ == null) {
        pointOne_ = null;
      } else {
        pointOne_ = null;
        pointOneBuilder_ = null;
      }
      if (pointTwoBuilder_ == null) {
        pointTwo_ = null;
      } else {
        pointTwo_ = null;
        pointTwoBuilder_ = null;
      }
      if (xLLCornerBuilder_ == null) {
        xLLCorner_ = null;
      } else {
        xLLCorner_ = null;
        xLLCornerBuilder_ = null;
      }
      if (yLLCornerBuilder_ == null) {
        yLLCorner_ = null;
      } else {
        yLLCorner_ = null;
        yLLCornerBuilder_ = null;
      }
      if (resolutionBuilder_ == null) {
        resolution_ = null;
      } else {
        resolution_ = null;
        resolutionBuilder_ = null;
      }
      if (landscapeBuilder_ == null) {
        landscape_ = null;
      } else {
        landscape_ = null;
        landscapeBuilder_ = null;
      }
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      comments_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      if (filterBuilder_ == null) {
        filter_ = null;
      } else {
        filter_ = null;
        filterBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.wise.grid.proto.CwfgmFilter.internal_static_WISE_GridProto_CwfgmReplaceGridFilter_descriptor;
    }

    @java.lang.Override
    public ca.wise.grid.proto.CwfgmReplaceGridFilter getDefaultInstanceForType() {
      return ca.wise.grid.proto.CwfgmReplaceGridFilter.getDefaultInstance();
    }

    @java.lang.Override
    public ca.wise.grid.proto.CwfgmReplaceGridFilter build() {
      ca.wise.grid.proto.CwfgmReplaceGridFilter result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.wise.grid.proto.CwfgmReplaceGridFilter buildPartial() {
      ca.wise.grid.proto.CwfgmReplaceGridFilter result = new ca.wise.grid.proto.CwfgmReplaceGridFilter(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.version_ = version_;
      if (pointOneBuilder_ == null) {
        result.pointOne_ = pointOne_;
      } else {
        result.pointOne_ = pointOneBuilder_.build();
      }
      if (pointTwoBuilder_ == null) {
        result.pointTwo_ = pointTwo_;
      } else {
        result.pointTwo_ = pointTwoBuilder_.build();
      }
      if (xLLCornerBuilder_ == null) {
        result.xLLCorner_ = xLLCorner_;
      } else {
        result.xLLCorner_ = xLLCornerBuilder_.build();
      }
      if (yLLCornerBuilder_ == null) {
        result.yLLCorner_ = yLLCorner_;
      } else {
        result.yLLCorner_ = yLLCornerBuilder_.build();
      }
      if (resolutionBuilder_ == null) {
        result.resolution_ = resolution_;
      } else {
        result.resolution_ = resolutionBuilder_.build();
      }
      if (landscapeBuilder_ == null) {
        result.landscape_ = landscape_;
      } else {
        result.landscape_ = landscapeBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.comments_ = comments_;
      if (filterBuilder_ == null) {
        result.filter_ = filter_;
      } else {
        result.filter_ = filterBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.wise.grid.proto.CwfgmReplaceGridFilter) {
        return mergeFrom((ca.wise.grid.proto.CwfgmReplaceGridFilter)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.wise.grid.proto.CwfgmReplaceGridFilter other) {
      if (other == ca.wise.grid.proto.CwfgmReplaceGridFilter.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (other.hasPointOne()) {
        mergePointOne(other.getPointOne());
      }
      if (other.hasPointTwo()) {
        mergePointTwo(other.getPointTwo());
      }
      if (other.hasXLLCorner()) {
        mergeXLLCorner(other.getXLLCorner());
      }
      if (other.hasYLLCorner()) {
        mergeYLLCorner(other.getYLLCorner());
      }
      if (other.hasResolution()) {
        mergeResolution(other.getResolution());
      }
      if (other.hasLandscape()) {
        mergeLandscape(other.getLandscape());
      }
      if (other.hasName()) {
        bitField0_ |= 0x00000001;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasComments()) {
        bitField0_ |= 0x00000002;
        comments_ = other.comments_;
        onChanged();
      }
      if (other.hasFilter()) {
        mergeFilter(other.getFilter());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.wise.grid.proto.CwfgmReplaceGridFilter parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.wise.grid.proto.CwfgmReplaceGridFilter) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int version_ ;
    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <code>int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private ca.hss.math.proto.GeoPoint pointOne_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.GeoPoint, ca.hss.math.proto.GeoPoint.Builder, ca.hss.math.proto.GeoPointOrBuilder> pointOneBuilder_;
    /**
     * <code>.Geography.GeoPoint pointOne = 2;</code>
     * @return Whether the pointOne field is set.
     */
    public boolean hasPointOne() {
      return pointOneBuilder_ != null || pointOne_ != null;
    }
    /**
     * <code>.Geography.GeoPoint pointOne = 2;</code>
     * @return The pointOne.
     */
    public ca.hss.math.proto.GeoPoint getPointOne() {
      if (pointOneBuilder_ == null) {
        return pointOne_ == null ? ca.hss.math.proto.GeoPoint.getDefaultInstance() : pointOne_;
      } else {
        return pointOneBuilder_.getMessage();
      }
    }
    /**
     * <code>.Geography.GeoPoint pointOne = 2;</code>
     */
    public Builder setPointOne(ca.hss.math.proto.GeoPoint value) {
      if (pointOneBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pointOne_ = value;
        onChanged();
      } else {
        pointOneBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Geography.GeoPoint pointOne = 2;</code>
     */
    public Builder setPointOne(
        ca.hss.math.proto.GeoPoint.Builder builderForValue) {
      if (pointOneBuilder_ == null) {
        pointOne_ = builderForValue.build();
        onChanged();
      } else {
        pointOneBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Geography.GeoPoint pointOne = 2;</code>
     */
    public Builder mergePointOne(ca.hss.math.proto.GeoPoint value) {
      if (pointOneBuilder_ == null) {
        if (pointOne_ != null) {
          pointOne_ =
            ca.hss.math.proto.GeoPoint.newBuilder(pointOne_).mergeFrom(value).buildPartial();
        } else {
          pointOne_ = value;
        }
        onChanged();
      } else {
        pointOneBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Geography.GeoPoint pointOne = 2;</code>
     */
    public Builder clearPointOne() {
      if (pointOneBuilder_ == null) {
        pointOne_ = null;
        onChanged();
      } else {
        pointOne_ = null;
        pointOneBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Geography.GeoPoint pointOne = 2;</code>
     */
    public ca.hss.math.proto.GeoPoint.Builder getPointOneBuilder() {
      
      onChanged();
      return getPointOneFieldBuilder().getBuilder();
    }
    /**
     * <code>.Geography.GeoPoint pointOne = 2;</code>
     */
    public ca.hss.math.proto.GeoPointOrBuilder getPointOneOrBuilder() {
      if (pointOneBuilder_ != null) {
        return pointOneBuilder_.getMessageOrBuilder();
      } else {
        return pointOne_ == null ?
            ca.hss.math.proto.GeoPoint.getDefaultInstance() : pointOne_;
      }
    }
    /**
     * <code>.Geography.GeoPoint pointOne = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.GeoPoint, ca.hss.math.proto.GeoPoint.Builder, ca.hss.math.proto.GeoPointOrBuilder> 
        getPointOneFieldBuilder() {
      if (pointOneBuilder_ == null) {
        pointOneBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.hss.math.proto.GeoPoint, ca.hss.math.proto.GeoPoint.Builder, ca.hss.math.proto.GeoPointOrBuilder>(
                getPointOne(),
                getParentForChildren(),
                isClean());
        pointOne_ = null;
      }
      return pointOneBuilder_;
    }

    private ca.hss.math.proto.GeoPoint pointTwo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.GeoPoint, ca.hss.math.proto.GeoPoint.Builder, ca.hss.math.proto.GeoPointOrBuilder> pointTwoBuilder_;
    /**
     * <code>.Geography.GeoPoint pointTwo = 3;</code>
     * @return Whether the pointTwo field is set.
     */
    public boolean hasPointTwo() {
      return pointTwoBuilder_ != null || pointTwo_ != null;
    }
    /**
     * <code>.Geography.GeoPoint pointTwo = 3;</code>
     * @return The pointTwo.
     */
    public ca.hss.math.proto.GeoPoint getPointTwo() {
      if (pointTwoBuilder_ == null) {
        return pointTwo_ == null ? ca.hss.math.proto.GeoPoint.getDefaultInstance() : pointTwo_;
      } else {
        return pointTwoBuilder_.getMessage();
      }
    }
    /**
     * <code>.Geography.GeoPoint pointTwo = 3;</code>
     */
    public Builder setPointTwo(ca.hss.math.proto.GeoPoint value) {
      if (pointTwoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pointTwo_ = value;
        onChanged();
      } else {
        pointTwoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Geography.GeoPoint pointTwo = 3;</code>
     */
    public Builder setPointTwo(
        ca.hss.math.proto.GeoPoint.Builder builderForValue) {
      if (pointTwoBuilder_ == null) {
        pointTwo_ = builderForValue.build();
        onChanged();
      } else {
        pointTwoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Geography.GeoPoint pointTwo = 3;</code>
     */
    public Builder mergePointTwo(ca.hss.math.proto.GeoPoint value) {
      if (pointTwoBuilder_ == null) {
        if (pointTwo_ != null) {
          pointTwo_ =
            ca.hss.math.proto.GeoPoint.newBuilder(pointTwo_).mergeFrom(value).buildPartial();
        } else {
          pointTwo_ = value;
        }
        onChanged();
      } else {
        pointTwoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Geography.GeoPoint pointTwo = 3;</code>
     */
    public Builder clearPointTwo() {
      if (pointTwoBuilder_ == null) {
        pointTwo_ = null;
        onChanged();
      } else {
        pointTwo_ = null;
        pointTwoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Geography.GeoPoint pointTwo = 3;</code>
     */
    public ca.hss.math.proto.GeoPoint.Builder getPointTwoBuilder() {
      
      onChanged();
      return getPointTwoFieldBuilder().getBuilder();
    }
    /**
     * <code>.Geography.GeoPoint pointTwo = 3;</code>
     */
    public ca.hss.math.proto.GeoPointOrBuilder getPointTwoOrBuilder() {
      if (pointTwoBuilder_ != null) {
        return pointTwoBuilder_.getMessageOrBuilder();
      } else {
        return pointTwo_ == null ?
            ca.hss.math.proto.GeoPoint.getDefaultInstance() : pointTwo_;
      }
    }
    /**
     * <code>.Geography.GeoPoint pointTwo = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.GeoPoint, ca.hss.math.proto.GeoPoint.Builder, ca.hss.math.proto.GeoPointOrBuilder> 
        getPointTwoFieldBuilder() {
      if (pointTwoBuilder_ == null) {
        pointTwoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.hss.math.proto.GeoPoint, ca.hss.math.proto.GeoPoint.Builder, ca.hss.math.proto.GeoPointOrBuilder>(
                getPointTwo(),
                getParentForChildren(),
                isClean());
        pointTwo_ = null;
      }
      return pointTwoBuilder_;
    }

    private ca.hss.math.proto.Double xLLCorner_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> xLLCornerBuilder_;
    /**
     * <code>.Math.Double xLLCorner = 4;</code>
     * @return Whether the xLLCorner field is set.
     */
    public boolean hasXLLCorner() {
      return xLLCornerBuilder_ != null || xLLCorner_ != null;
    }
    /**
     * <code>.Math.Double xLLCorner = 4;</code>
     * @return The xLLCorner.
     */
    public ca.hss.math.proto.Double getXLLCorner() {
      if (xLLCornerBuilder_ == null) {
        return xLLCorner_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : xLLCorner_;
      } else {
        return xLLCornerBuilder_.getMessage();
      }
    }
    /**
     * <code>.Math.Double xLLCorner = 4;</code>
     */
    public Builder setXLLCorner(ca.hss.math.proto.Double value) {
      if (xLLCornerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        xLLCorner_ = value;
        onChanged();
      } else {
        xLLCornerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Math.Double xLLCorner = 4;</code>
     */
    public Builder setXLLCorner(
        ca.hss.math.proto.Double.Builder builderForValue) {
      if (xLLCornerBuilder_ == null) {
        xLLCorner_ = builderForValue.build();
        onChanged();
      } else {
        xLLCornerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Math.Double xLLCorner = 4;</code>
     */
    public Builder mergeXLLCorner(ca.hss.math.proto.Double value) {
      if (xLLCornerBuilder_ == null) {
        if (xLLCorner_ != null) {
          xLLCorner_ =
            ca.hss.math.proto.Double.newBuilder(xLLCorner_).mergeFrom(value).buildPartial();
        } else {
          xLLCorner_ = value;
        }
        onChanged();
      } else {
        xLLCornerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Math.Double xLLCorner = 4;</code>
     */
    public Builder clearXLLCorner() {
      if (xLLCornerBuilder_ == null) {
        xLLCorner_ = null;
        onChanged();
      } else {
        xLLCorner_ = null;
        xLLCornerBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Math.Double xLLCorner = 4;</code>
     */
    public ca.hss.math.proto.Double.Builder getXLLCornerBuilder() {
      
      onChanged();
      return getXLLCornerFieldBuilder().getBuilder();
    }
    /**
     * <code>.Math.Double xLLCorner = 4;</code>
     */
    public ca.hss.math.proto.DoubleOrBuilder getXLLCornerOrBuilder() {
      if (xLLCornerBuilder_ != null) {
        return xLLCornerBuilder_.getMessageOrBuilder();
      } else {
        return xLLCorner_ == null ?
            ca.hss.math.proto.Double.getDefaultInstance() : xLLCorner_;
      }
    }
    /**
     * <code>.Math.Double xLLCorner = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> 
        getXLLCornerFieldBuilder() {
      if (xLLCornerBuilder_ == null) {
        xLLCornerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder>(
                getXLLCorner(),
                getParentForChildren(),
                isClean());
        xLLCorner_ = null;
      }
      return xLLCornerBuilder_;
    }

    private ca.hss.math.proto.Double yLLCorner_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> yLLCornerBuilder_;
    /**
     * <code>.Math.Double yLLCorner = 5;</code>
     * @return Whether the yLLCorner field is set.
     */
    public boolean hasYLLCorner() {
      return yLLCornerBuilder_ != null || yLLCorner_ != null;
    }
    /**
     * <code>.Math.Double yLLCorner = 5;</code>
     * @return The yLLCorner.
     */
    public ca.hss.math.proto.Double getYLLCorner() {
      if (yLLCornerBuilder_ == null) {
        return yLLCorner_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : yLLCorner_;
      } else {
        return yLLCornerBuilder_.getMessage();
      }
    }
    /**
     * <code>.Math.Double yLLCorner = 5;</code>
     */
    public Builder setYLLCorner(ca.hss.math.proto.Double value) {
      if (yLLCornerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        yLLCorner_ = value;
        onChanged();
      } else {
        yLLCornerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Math.Double yLLCorner = 5;</code>
     */
    public Builder setYLLCorner(
        ca.hss.math.proto.Double.Builder builderForValue) {
      if (yLLCornerBuilder_ == null) {
        yLLCorner_ = builderForValue.build();
        onChanged();
      } else {
        yLLCornerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Math.Double yLLCorner = 5;</code>
     */
    public Builder mergeYLLCorner(ca.hss.math.proto.Double value) {
      if (yLLCornerBuilder_ == null) {
        if (yLLCorner_ != null) {
          yLLCorner_ =
            ca.hss.math.proto.Double.newBuilder(yLLCorner_).mergeFrom(value).buildPartial();
        } else {
          yLLCorner_ = value;
        }
        onChanged();
      } else {
        yLLCornerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Math.Double yLLCorner = 5;</code>
     */
    public Builder clearYLLCorner() {
      if (yLLCornerBuilder_ == null) {
        yLLCorner_ = null;
        onChanged();
      } else {
        yLLCorner_ = null;
        yLLCornerBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Math.Double yLLCorner = 5;</code>
     */
    public ca.hss.math.proto.Double.Builder getYLLCornerBuilder() {
      
      onChanged();
      return getYLLCornerFieldBuilder().getBuilder();
    }
    /**
     * <code>.Math.Double yLLCorner = 5;</code>
     */
    public ca.hss.math.proto.DoubleOrBuilder getYLLCornerOrBuilder() {
      if (yLLCornerBuilder_ != null) {
        return yLLCornerBuilder_.getMessageOrBuilder();
      } else {
        return yLLCorner_ == null ?
            ca.hss.math.proto.Double.getDefaultInstance() : yLLCorner_;
      }
    }
    /**
     * <code>.Math.Double yLLCorner = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> 
        getYLLCornerFieldBuilder() {
      if (yLLCornerBuilder_ == null) {
        yLLCornerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder>(
                getYLLCorner(),
                getParentForChildren(),
                isClean());
        yLLCorner_ = null;
      }
      return yLLCornerBuilder_;
    }

    private ca.hss.math.proto.Double resolution_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> resolutionBuilder_;
    /**
     * <code>.Math.Double resolution = 6;</code>
     * @return Whether the resolution field is set.
     */
    public boolean hasResolution() {
      return resolutionBuilder_ != null || resolution_ != null;
    }
    /**
     * <code>.Math.Double resolution = 6;</code>
     * @return The resolution.
     */
    public ca.hss.math.proto.Double getResolution() {
      if (resolutionBuilder_ == null) {
        return resolution_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : resolution_;
      } else {
        return resolutionBuilder_.getMessage();
      }
    }
    /**
     * <code>.Math.Double resolution = 6;</code>
     */
    public Builder setResolution(ca.hss.math.proto.Double value) {
      if (resolutionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resolution_ = value;
        onChanged();
      } else {
        resolutionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Math.Double resolution = 6;</code>
     */
    public Builder setResolution(
        ca.hss.math.proto.Double.Builder builderForValue) {
      if (resolutionBuilder_ == null) {
        resolution_ = builderForValue.build();
        onChanged();
      } else {
        resolutionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Math.Double resolution = 6;</code>
     */
    public Builder mergeResolution(ca.hss.math.proto.Double value) {
      if (resolutionBuilder_ == null) {
        if (resolution_ != null) {
          resolution_ =
            ca.hss.math.proto.Double.newBuilder(resolution_).mergeFrom(value).buildPartial();
        } else {
          resolution_ = value;
        }
        onChanged();
      } else {
        resolutionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Math.Double resolution = 6;</code>
     */
    public Builder clearResolution() {
      if (resolutionBuilder_ == null) {
        resolution_ = null;
        onChanged();
      } else {
        resolution_ = null;
        resolutionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Math.Double resolution = 6;</code>
     */
    public ca.hss.math.proto.Double.Builder getResolutionBuilder() {
      
      onChanged();
      return getResolutionFieldBuilder().getBuilder();
    }
    /**
     * <code>.Math.Double resolution = 6;</code>
     */
    public ca.hss.math.proto.DoubleOrBuilder getResolutionOrBuilder() {
      if (resolutionBuilder_ != null) {
        return resolutionBuilder_.getMessageOrBuilder();
      } else {
        return resolution_ == null ?
            ca.hss.math.proto.Double.getDefaultInstance() : resolution_;
      }
    }
    /**
     * <code>.Math.Double resolution = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> 
        getResolutionFieldBuilder() {
      if (resolutionBuilder_ == null) {
        resolutionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder>(
                getResolution(),
                getParentForChildren(),
                isClean());
        resolution_ = null;
      }
      return resolutionBuilder_;
    }

    private com.google.protobuf.BoolValue landscape_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> landscapeBuilder_;
    /**
     * <code>.google.protobuf.BoolValue landscape = 7;</code>
     * @return Whether the landscape field is set.
     */
    public boolean hasLandscape() {
      return landscapeBuilder_ != null || landscape_ != null;
    }
    /**
     * <code>.google.protobuf.BoolValue landscape = 7;</code>
     * @return The landscape.
     */
    public com.google.protobuf.BoolValue getLandscape() {
      if (landscapeBuilder_ == null) {
        return landscape_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : landscape_;
      } else {
        return landscapeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.BoolValue landscape = 7;</code>
     */
    public Builder setLandscape(com.google.protobuf.BoolValue value) {
      if (landscapeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        landscape_ = value;
        onChanged();
      } else {
        landscapeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue landscape = 7;</code>
     */
    public Builder setLandscape(
        com.google.protobuf.BoolValue.Builder builderForValue) {
      if (landscapeBuilder_ == null) {
        landscape_ = builderForValue.build();
        onChanged();
      } else {
        landscapeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue landscape = 7;</code>
     */
    public Builder mergeLandscape(com.google.protobuf.BoolValue value) {
      if (landscapeBuilder_ == null) {
        if (landscape_ != null) {
          landscape_ =
            com.google.protobuf.BoolValue.newBuilder(landscape_).mergeFrom(value).buildPartial();
        } else {
          landscape_ = value;
        }
        onChanged();
      } else {
        landscapeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue landscape = 7;</code>
     */
    public Builder clearLandscape() {
      if (landscapeBuilder_ == null) {
        landscape_ = null;
        onChanged();
      } else {
        landscape_ = null;
        landscapeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue landscape = 7;</code>
     */
    public com.google.protobuf.BoolValue.Builder getLandscapeBuilder() {
      
      onChanged();
      return getLandscapeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.BoolValue landscape = 7;</code>
     */
    public com.google.protobuf.BoolValueOrBuilder getLandscapeOrBuilder() {
      if (landscapeBuilder_ != null) {
        return landscapeBuilder_.getMessageOrBuilder();
      } else {
        return landscape_ == null ?
            com.google.protobuf.BoolValue.getDefaultInstance() : landscape_;
      }
    }
    /**
     * <code>.google.protobuf.BoolValue landscape = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> 
        getLandscapeFieldBuilder() {
      if (landscapeBuilder_ == null) {
        landscapeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder>(
                getLandscape(),
                getParentForChildren(),
                isClean());
        landscape_ = null;
      }
      return landscapeBuilder_;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * not really optional but need to be able to suppress it in the old file format
     * </pre>
     *
     * <code>string name = 8;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * not really optional but need to be able to suppress it in the old file format
     * </pre>
     *
     * <code>string name = 8;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * not really optional but need to be able to suppress it in the old file format
     * </pre>
     *
     * <code>string name = 8;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * not really optional but need to be able to suppress it in the old file format
     * </pre>
     *
     * <code>string name = 8;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * not really optional but need to be able to suppress it in the old file format
     * </pre>
     *
     * <code>string name = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * not really optional but need to be able to suppress it in the old file format
     * </pre>
     *
     * <code>string name = 8;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object comments_ = "";
    /**
     * <code>string comments = 9;</code>
     * @return Whether the comments field is set.
     */
    public boolean hasComments() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>string comments = 9;</code>
     * @return The comments.
     */
    public java.lang.String getComments() {
      java.lang.Object ref = comments_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        comments_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string comments = 9;</code>
     * @return The bytes for comments.
     */
    public com.google.protobuf.ByteString
        getCommentsBytes() {
      java.lang.Object ref = comments_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        comments_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string comments = 9;</code>
     * @param value The comments to set.
     * @return This builder for chaining.
     */
    public Builder setComments(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      comments_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string comments = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearComments() {
      bitField0_ = (bitField0_ & ~0x00000002);
      comments_ = getDefaultInstance().getComments();
      onChanged();
      return this;
    }
    /**
     * <code>string comments = 9;</code>
     * @param value The bytes for comments to set.
     * @return This builder for chaining.
     */
    public Builder setCommentsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      comments_ = value;
      onChanged();
      return this;
    }

    private ca.wise.grid.proto.CwfgmReplaceGridFilterBase filter_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.grid.proto.CwfgmReplaceGridFilterBase, ca.wise.grid.proto.CwfgmReplaceGridFilterBase.Builder, ca.wise.grid.proto.CwfgmReplaceGridFilterBaseOrBuilder> filterBuilder_;
    /**
     * <code>.WISE.GridProto.CwfgmReplaceGridFilterBase filter = 10;</code>
     * @return Whether the filter field is set.
     */
    public boolean hasFilter() {
      return filterBuilder_ != null || filter_ != null;
    }
    /**
     * <code>.WISE.GridProto.CwfgmReplaceGridFilterBase filter = 10;</code>
     * @return The filter.
     */
    public ca.wise.grid.proto.CwfgmReplaceGridFilterBase getFilter() {
      if (filterBuilder_ == null) {
        return filter_ == null ? ca.wise.grid.proto.CwfgmReplaceGridFilterBase.getDefaultInstance() : filter_;
      } else {
        return filterBuilder_.getMessage();
      }
    }
    /**
     * <code>.WISE.GridProto.CwfgmReplaceGridFilterBase filter = 10;</code>
     */
    public Builder setFilter(ca.wise.grid.proto.CwfgmReplaceGridFilterBase value) {
      if (filterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        filter_ = value;
        onChanged();
      } else {
        filterBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.WISE.GridProto.CwfgmReplaceGridFilterBase filter = 10;</code>
     */
    public Builder setFilter(
        ca.wise.grid.proto.CwfgmReplaceGridFilterBase.Builder builderForValue) {
      if (filterBuilder_ == null) {
        filter_ = builderForValue.build();
        onChanged();
      } else {
        filterBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.WISE.GridProto.CwfgmReplaceGridFilterBase filter = 10;</code>
     */
    public Builder mergeFilter(ca.wise.grid.proto.CwfgmReplaceGridFilterBase value) {
      if (filterBuilder_ == null) {
        if (filter_ != null) {
          filter_ =
            ca.wise.grid.proto.CwfgmReplaceGridFilterBase.newBuilder(filter_).mergeFrom(value).buildPartial();
        } else {
          filter_ = value;
        }
        onChanged();
      } else {
        filterBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.WISE.GridProto.CwfgmReplaceGridFilterBase filter = 10;</code>
     */
    public Builder clearFilter() {
      if (filterBuilder_ == null) {
        filter_ = null;
        onChanged();
      } else {
        filter_ = null;
        filterBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.WISE.GridProto.CwfgmReplaceGridFilterBase filter = 10;</code>
     */
    public ca.wise.grid.proto.CwfgmReplaceGridFilterBase.Builder getFilterBuilder() {
      
      onChanged();
      return getFilterFieldBuilder().getBuilder();
    }
    /**
     * <code>.WISE.GridProto.CwfgmReplaceGridFilterBase filter = 10;</code>
     */
    public ca.wise.grid.proto.CwfgmReplaceGridFilterBaseOrBuilder getFilterOrBuilder() {
      if (filterBuilder_ != null) {
        return filterBuilder_.getMessageOrBuilder();
      } else {
        return filter_ == null ?
            ca.wise.grid.proto.CwfgmReplaceGridFilterBase.getDefaultInstance() : filter_;
      }
    }
    /**
     * <code>.WISE.GridProto.CwfgmReplaceGridFilterBase filter = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.grid.proto.CwfgmReplaceGridFilterBase, ca.wise.grid.proto.CwfgmReplaceGridFilterBase.Builder, ca.wise.grid.proto.CwfgmReplaceGridFilterBaseOrBuilder> 
        getFilterFieldBuilder() {
      if (filterBuilder_ == null) {
        filterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.grid.proto.CwfgmReplaceGridFilterBase, ca.wise.grid.proto.CwfgmReplaceGridFilterBase.Builder, ca.wise.grid.proto.CwfgmReplaceGridFilterBaseOrBuilder>(
                getFilter(),
                getParentForChildren(),
                isClean());
        filter_ = null;
      }
      return filterBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WISE.GridProto.CwfgmReplaceGridFilter)
  }

  // @@protoc_insertion_point(class_scope:WISE.GridProto.CwfgmReplaceGridFilter)
  private static final ca.wise.grid.proto.CwfgmReplaceGridFilter DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.wise.grid.proto.CwfgmReplaceGridFilter();
  }

  public static ca.wise.grid.proto.CwfgmReplaceGridFilter getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CwfgmReplaceGridFilter>
      PARSER = new com.google.protobuf.AbstractParser<CwfgmReplaceGridFilter>() {
    @java.lang.Override
    public CwfgmReplaceGridFilter parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CwfgmReplaceGridFilter(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CwfgmReplaceGridFilter> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CwfgmReplaceGridFilter> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.wise.grid.proto.CwfgmReplaceGridFilter getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

