// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cwfgmGrid.proto

package ca.wise.grid.proto;

public interface CwfgmGridOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.GridProto.CwfgmGrid)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>.google.protobuf.UInt32Value xSize = 2;</code>
   * @return Whether the xSize field is set.
   */
  boolean hasXSize();
  /**
   * <code>.google.protobuf.UInt32Value xSize = 2;</code>
   * @return The xSize.
   */
  com.google.protobuf.UInt32Value getXSize();
  /**
   * <code>.google.protobuf.UInt32Value xSize = 2;</code>
   */
  com.google.protobuf.UInt32ValueOrBuilder getXSizeOrBuilder();

  /**
   * <code>.google.protobuf.UInt32Value ySize = 3;</code>
   * @return Whether the ySize field is set.
   */
  boolean hasYSize();
  /**
   * <code>.google.protobuf.UInt32Value ySize = 3;</code>
   * @return The ySize.
   */
  com.google.protobuf.UInt32Value getYSize();
  /**
   * <code>.google.protobuf.UInt32Value ySize = 3;</code>
   */
  com.google.protobuf.UInt32ValueOrBuilder getYSizeOrBuilder();

  /**
   * <code>.Math.Double xLLCorner = 4;</code>
   * @return Whether the xLLCorner field is set.
   */
  boolean hasXLLCorner();
  /**
   * <code>.Math.Double xLLCorner = 4;</code>
   * @return The xLLCorner.
   */
  ca.hss.math.proto.Double getXLLCorner();
  /**
   * <code>.Math.Double xLLCorner = 4;</code>
   */
  ca.hss.math.proto.DoubleOrBuilder getXLLCornerOrBuilder();

  /**
   * <code>.Math.Double yLLCorner = 5;</code>
   * @return Whether the yLLCorner field is set.
   */
  boolean hasYLLCorner();
  /**
   * <code>.Math.Double yLLCorner = 5;</code>
   * @return The yLLCorner.
   */
  ca.hss.math.proto.Double getYLLCorner();
  /**
   * <code>.Math.Double yLLCorner = 5;</code>
   */
  ca.hss.math.proto.DoubleOrBuilder getYLLCornerOrBuilder();

  /**
   * <code>.Math.Double resolution = 6;</code>
   * @return Whether the resolution field is set.
   */
  boolean hasResolution();
  /**
   * <code>.Math.Double resolution = 6;</code>
   * @return The resolution.
   */
  ca.hss.math.proto.Double getResolution();
  /**
   * <code>.Math.Double resolution = 6;</code>
   */
  ca.hss.math.proto.DoubleOrBuilder getResolutionOrBuilder();

  /**
   * <code>.Math.Coordinate llLocation = 7;</code>
   * @return Whether the llLocation field is set.
   */
  boolean hasLlLocation();
  /**
   * <code>.Math.Coordinate llLocation = 7;</code>
   * @return The llLocation.
   */
  ca.hss.math.proto.Coordinate getLlLocation();
  /**
   * <code>.Math.Coordinate llLocation = 7;</code>
   */
  ca.hss.math.proto.CoordinateOrBuilder getLlLocationOrBuilder();

  /**
   * <code>.Math.Double nodataElevation = 8;</code>
   * @return Whether the nodataElevation field is set.
   */
  boolean hasNodataElevation();
  /**
   * <code>.Math.Double nodataElevation = 8;</code>
   * @return The nodataElevation.
   */
  ca.hss.math.proto.Double getNodataElevation();
  /**
   * <code>.Math.Double nodataElevation = 8;</code>
   */
  ca.hss.math.proto.DoubleOrBuilder getNodataElevationOrBuilder();

  /**
   * <code>.WISE.GridProto.CwfgmGrid.FuelMapFile fuelMap = 9;</code>
   * @return Whether the fuelMap field is set.
   */
  boolean hasFuelMap();
  /**
   * <code>.WISE.GridProto.CwfgmGrid.FuelMapFile fuelMap = 9;</code>
   * @return The fuelMap.
   */
  ca.wise.grid.proto.CwfgmGrid.FuelMapFile getFuelMap();
  /**
   * <code>.WISE.GridProto.CwfgmGrid.FuelMapFile fuelMap = 9;</code>
   */
  ca.wise.grid.proto.CwfgmGrid.FuelMapFileOrBuilder getFuelMapOrBuilder();

  /**
   * <code>.WISE.GridProto.CwfgmGrid.ElevationFile elevation = 10;</code>
   * @return Whether the elevation field is set.
   */
  boolean hasElevation();
  /**
   * <code>.WISE.GridProto.CwfgmGrid.ElevationFile elevation = 10;</code>
   * @return The elevation.
   */
  ca.wise.grid.proto.CwfgmGrid.ElevationFile getElevation();
  /**
   * <code>.WISE.GridProto.CwfgmGrid.ElevationFile elevation = 10;</code>
   */
  ca.wise.grid.proto.CwfgmGrid.ElevationFileOrBuilder getElevationOrBuilder();

  /**
   * <code>.WISE.GridProto.CwfgmGrid.ProjectionFile projection = 11;</code>
   * @return Whether the projection field is set.
   */
  boolean hasProjection();
  /**
   * <code>.WISE.GridProto.CwfgmGrid.ProjectionFile projection = 11;</code>
   * @return The projection.
   */
  ca.wise.grid.proto.CwfgmGrid.ProjectionFile getProjection();
  /**
   * <code>.WISE.GridProto.CwfgmGrid.ProjectionFile projection = 11;</code>
   */
  ca.wise.grid.proto.CwfgmGrid.ProjectionFileOrBuilder getProjectionOrBuilder();
}
