// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cwfgmFuelMap.proto

package ca.wise.grid.proto;

/**
 * Protobuf type {@code WISE.GridProto.CwfgmFuelMap}
 */
public final class CwfgmFuelMap extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WISE.GridProto.CwfgmFuelMap)
    CwfgmFuelMapOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CwfgmFuelMap.newBuilder() to construct.
  private CwfgmFuelMap(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CwfgmFuelMap() {
    data_ = java.util.Collections.emptyList();
    lutFilename_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CwfgmFuelMap();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CwfgmFuelMap(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            version_ = input.readInt32();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              data_ = new java.util.ArrayList<ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData>();
              mutable_bitField0_ |= 0x00000001;
            }
            data_.add(
                input.readMessage(ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData.parser(), extensionRegistry));
            break;
          }
          case 24: {
            bitField0_ |= 0x00000001;
            importedLut_ = input.readBool();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000002;
            lutFilename_ = s;
            break;
          }
          case 40: {
            bitField0_ |= 0x00000004;
            showUnused_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        data_ = java.util.Collections.unmodifiableList(data_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.wise.grid.proto.CwfgmFuelMapOuterClass.internal_static_WISE_GridProto_CwfgmFuelMap_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.wise.grid.proto.CwfgmFuelMapOuterClass.internal_static_WISE_GridProto_CwfgmFuelMap_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.wise.grid.proto.CwfgmFuelMap.class, ca.wise.grid.proto.CwfgmFuelMap.Builder.class);
  }

  public interface CwfgmFuelDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WISE.GridProto.CwfgmFuelMap.CwfgmFuelData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 index = 1;</code>
     * @return The index.
     */
    int getIndex();

    /**
     * <code>int32 exportIndex = 2;</code>
     * @return The exportIndex.
     */
    int getExportIndex();

    /**
     * <code>.google.protobuf.Int32Value fuelIndex = 3;</code>
     * @return Whether the fuelIndex field is set.
     */
    boolean hasFuelIndex();
    /**
     * <code>.google.protobuf.Int32Value fuelIndex = 3;</code>
     * @return The fuelIndex.
     */
    com.google.protobuf.Int32Value getFuelIndex();
    /**
     * <code>.google.protobuf.Int32Value fuelIndex = 3;</code>
     */
    com.google.protobuf.Int32ValueOrBuilder getFuelIndexOrBuilder();

    /**
     * <code>.WISE.FuelProto.CcwfgmFuel fuelData = 4;</code>
     * @return Whether the fuelData field is set.
     */
    boolean hasFuelData();
    /**
     * <code>.WISE.FuelProto.CcwfgmFuel fuelData = 4;</code>
     * @return The fuelData.
     */
    ca.wise.fuel.proto.CcwfgmFuel getFuelData();
    /**
     * <code>.WISE.FuelProto.CcwfgmFuel fuelData = 4;</code>
     */
    ca.wise.fuel.proto.CcwfgmFuelOrBuilder getFuelDataOrBuilder();

    public ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData.FuelCase getFuelCase();
  }
  /**
   * Protobuf type {@code WISE.GridProto.CwfgmFuelMap.CwfgmFuelData}
   */
  public static final class CwfgmFuelData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:WISE.GridProto.CwfgmFuelMap.CwfgmFuelData)
      CwfgmFuelDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CwfgmFuelData.newBuilder() to construct.
    private CwfgmFuelData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CwfgmFuelData() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CwfgmFuelData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CwfgmFuelData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              index_ = input.readInt32();
              break;
            }
            case 16: {

              exportIndex_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.Int32Value.Builder subBuilder = null;
              if (fuelCase_ == 3) {
                subBuilder = ((com.google.protobuf.Int32Value) fuel_).toBuilder();
              }
              fuel_ =
                  input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.google.protobuf.Int32Value) fuel_);
                fuel_ = subBuilder.buildPartial();
              }
              fuelCase_ = 3;
              break;
            }
            case 34: {
              ca.wise.fuel.proto.CcwfgmFuel.Builder subBuilder = null;
              if (fuelCase_ == 4) {
                subBuilder = ((ca.wise.fuel.proto.CcwfgmFuel) fuel_).toBuilder();
              }
              fuel_ =
                  input.readMessage(ca.wise.fuel.proto.CcwfgmFuel.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((ca.wise.fuel.proto.CcwfgmFuel) fuel_);
                fuel_ = subBuilder.buildPartial();
              }
              fuelCase_ = 4;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.grid.proto.CwfgmFuelMapOuterClass.internal_static_WISE_GridProto_CwfgmFuelMap_CwfgmFuelData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.grid.proto.CwfgmFuelMapOuterClass.internal_static_WISE_GridProto_CwfgmFuelMap_CwfgmFuelData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData.class, ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData.Builder.class);
    }

    private int fuelCase_ = 0;
    private java.lang.Object fuel_;
    public enum FuelCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      FUELINDEX(3),
      FUELDATA(4),
      FUEL_NOT_SET(0);
      private final int value;
      private FuelCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static FuelCase valueOf(int value) {
        return forNumber(value);
      }

      public static FuelCase forNumber(int value) {
        switch (value) {
          case 3: return FUELINDEX;
          case 4: return FUELDATA;
          case 0: return FUEL_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public FuelCase
    getFuelCase() {
      return FuelCase.forNumber(
          fuelCase_);
    }

    public static final int INDEX_FIELD_NUMBER = 1;
    private int index_;
    /**
     * <code>int32 index = 1;</code>
     * @return The index.
     */
    @java.lang.Override
    public int getIndex() {
      return index_;
    }

    public static final int EXPORTINDEX_FIELD_NUMBER = 2;
    private int exportIndex_;
    /**
     * <code>int32 exportIndex = 2;</code>
     * @return The exportIndex.
     */
    @java.lang.Override
    public int getExportIndex() {
      return exportIndex_;
    }

    public static final int FUELINDEX_FIELD_NUMBER = 3;
    /**
     * <code>.google.protobuf.Int32Value fuelIndex = 3;</code>
     * @return Whether the fuelIndex field is set.
     */
    @java.lang.Override
    public boolean hasFuelIndex() {
      return fuelCase_ == 3;
    }
    /**
     * <code>.google.protobuf.Int32Value fuelIndex = 3;</code>
     * @return The fuelIndex.
     */
    @java.lang.Override
    public com.google.protobuf.Int32Value getFuelIndex() {
      if (fuelCase_ == 3) {
         return (com.google.protobuf.Int32Value) fuel_;
      }
      return com.google.protobuf.Int32Value.getDefaultInstance();
    }
    /**
     * <code>.google.protobuf.Int32Value fuelIndex = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Int32ValueOrBuilder getFuelIndexOrBuilder() {
      if (fuelCase_ == 3) {
         return (com.google.protobuf.Int32Value) fuel_;
      }
      return com.google.protobuf.Int32Value.getDefaultInstance();
    }

    public static final int FUELDATA_FIELD_NUMBER = 4;
    /**
     * <code>.WISE.FuelProto.CcwfgmFuel fuelData = 4;</code>
     * @return Whether the fuelData field is set.
     */
    @java.lang.Override
    public boolean hasFuelData() {
      return fuelCase_ == 4;
    }
    /**
     * <code>.WISE.FuelProto.CcwfgmFuel fuelData = 4;</code>
     * @return The fuelData.
     */
    @java.lang.Override
    public ca.wise.fuel.proto.CcwfgmFuel getFuelData() {
      if (fuelCase_ == 4) {
         return (ca.wise.fuel.proto.CcwfgmFuel) fuel_;
      }
      return ca.wise.fuel.proto.CcwfgmFuel.getDefaultInstance();
    }
    /**
     * <code>.WISE.FuelProto.CcwfgmFuel fuelData = 4;</code>
     */
    @java.lang.Override
    public ca.wise.fuel.proto.CcwfgmFuelOrBuilder getFuelDataOrBuilder() {
      if (fuelCase_ == 4) {
         return (ca.wise.fuel.proto.CcwfgmFuel) fuel_;
      }
      return ca.wise.fuel.proto.CcwfgmFuel.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (index_ != 0) {
        output.writeInt32(1, index_);
      }
      if (exportIndex_ != 0) {
        output.writeInt32(2, exportIndex_);
      }
      if (fuelCase_ == 3) {
        output.writeMessage(3, (com.google.protobuf.Int32Value) fuel_);
      }
      if (fuelCase_ == 4) {
        output.writeMessage(4, (ca.wise.fuel.proto.CcwfgmFuel) fuel_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (index_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, index_);
      }
      if (exportIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, exportIndex_);
      }
      if (fuelCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.google.protobuf.Int32Value) fuel_);
      }
      if (fuelCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (ca.wise.fuel.proto.CcwfgmFuel) fuel_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData)) {
        return super.equals(obj);
      }
      ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData other = (ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData) obj;

      if (getIndex()
          != other.getIndex()) return false;
      if (getExportIndex()
          != other.getExportIndex()) return false;
      if (!getFuelCase().equals(other.getFuelCase())) return false;
      switch (fuelCase_) {
        case 3:
          if (!getFuelIndex()
              .equals(other.getFuelIndex())) return false;
          break;
        case 4:
          if (!getFuelData()
              .equals(other.getFuelData())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getIndex();
      hash = (37 * hash) + EXPORTINDEX_FIELD_NUMBER;
      hash = (53 * hash) + getExportIndex();
      switch (fuelCase_) {
        case 3:
          hash = (37 * hash) + FUELINDEX_FIELD_NUMBER;
          hash = (53 * hash) + getFuelIndex().hashCode();
          break;
        case 4:
          hash = (37 * hash) + FUELDATA_FIELD_NUMBER;
          hash = (53 * hash) + getFuelData().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WISE.GridProto.CwfgmFuelMap.CwfgmFuelData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WISE.GridProto.CwfgmFuelMap.CwfgmFuelData)
        ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.wise.grid.proto.CwfgmFuelMapOuterClass.internal_static_WISE_GridProto_CwfgmFuelMap_CwfgmFuelData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.wise.grid.proto.CwfgmFuelMapOuterClass.internal_static_WISE_GridProto_CwfgmFuelMap_CwfgmFuelData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData.class, ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData.Builder.class);
      }

      // Construct using ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        index_ = 0;

        exportIndex_ = 0;

        fuelCase_ = 0;
        fuel_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.wise.grid.proto.CwfgmFuelMapOuterClass.internal_static_WISE_GridProto_CwfgmFuelMap_CwfgmFuelData_descriptor;
      }

      @java.lang.Override
      public ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData getDefaultInstanceForType() {
        return ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData.getDefaultInstance();
      }

      @java.lang.Override
      public ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData build() {
        ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData buildPartial() {
        ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData result = new ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData(this);
        result.index_ = index_;
        result.exportIndex_ = exportIndex_;
        if (fuelCase_ == 3) {
          if (fuelIndexBuilder_ == null) {
            result.fuel_ = fuel_;
          } else {
            result.fuel_ = fuelIndexBuilder_.build();
          }
        }
        if (fuelCase_ == 4) {
          if (fuelDataBuilder_ == null) {
            result.fuel_ = fuel_;
          } else {
            result.fuel_ = fuelDataBuilder_.build();
          }
        }
        result.fuelCase_ = fuelCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData) {
          return mergeFrom((ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData other) {
        if (other == ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData.getDefaultInstance()) return this;
        if (other.getIndex() != 0) {
          setIndex(other.getIndex());
        }
        if (other.getExportIndex() != 0) {
          setExportIndex(other.getExportIndex());
        }
        switch (other.getFuelCase()) {
          case FUELINDEX: {
            mergeFuelIndex(other.getFuelIndex());
            break;
          }
          case FUELDATA: {
            mergeFuelData(other.getFuelData());
            break;
          }
          case FUEL_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int fuelCase_ = 0;
      private java.lang.Object fuel_;
      public FuelCase
          getFuelCase() {
        return FuelCase.forNumber(
            fuelCase_);
      }

      public Builder clearFuel() {
        fuelCase_ = 0;
        fuel_ = null;
        onChanged();
        return this;
      }


      private int index_ ;
      /**
       * <code>int32 index = 1;</code>
       * @return The index.
       */
      @java.lang.Override
      public int getIndex() {
        return index_;
      }
      /**
       * <code>int32 index = 1;</code>
       * @param value The index to set.
       * @return This builder for chaining.
       */
      public Builder setIndex(int value) {
        
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 index = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIndex() {
        
        index_ = 0;
        onChanged();
        return this;
      }

      private int exportIndex_ ;
      /**
       * <code>int32 exportIndex = 2;</code>
       * @return The exportIndex.
       */
      @java.lang.Override
      public int getExportIndex() {
        return exportIndex_;
      }
      /**
       * <code>int32 exportIndex = 2;</code>
       * @param value The exportIndex to set.
       * @return This builder for chaining.
       */
      public Builder setExportIndex(int value) {
        
        exportIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 exportIndex = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearExportIndex() {
        
        exportIndex_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> fuelIndexBuilder_;
      /**
       * <code>.google.protobuf.Int32Value fuelIndex = 3;</code>
       * @return Whether the fuelIndex field is set.
       */
      @java.lang.Override
      public boolean hasFuelIndex() {
        return fuelCase_ == 3;
      }
      /**
       * <code>.google.protobuf.Int32Value fuelIndex = 3;</code>
       * @return The fuelIndex.
       */
      @java.lang.Override
      public com.google.protobuf.Int32Value getFuelIndex() {
        if (fuelIndexBuilder_ == null) {
          if (fuelCase_ == 3) {
            return (com.google.protobuf.Int32Value) fuel_;
          }
          return com.google.protobuf.Int32Value.getDefaultInstance();
        } else {
          if (fuelCase_ == 3) {
            return fuelIndexBuilder_.getMessage();
          }
          return com.google.protobuf.Int32Value.getDefaultInstance();
        }
      }
      /**
       * <code>.google.protobuf.Int32Value fuelIndex = 3;</code>
       */
      public Builder setFuelIndex(com.google.protobuf.Int32Value value) {
        if (fuelIndexBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fuel_ = value;
          onChanged();
        } else {
          fuelIndexBuilder_.setMessage(value);
        }
        fuelCase_ = 3;
        return this;
      }
      /**
       * <code>.google.protobuf.Int32Value fuelIndex = 3;</code>
       */
      public Builder setFuelIndex(
          com.google.protobuf.Int32Value.Builder builderForValue) {
        if (fuelIndexBuilder_ == null) {
          fuel_ = builderForValue.build();
          onChanged();
        } else {
          fuelIndexBuilder_.setMessage(builderForValue.build());
        }
        fuelCase_ = 3;
        return this;
      }
      /**
       * <code>.google.protobuf.Int32Value fuelIndex = 3;</code>
       */
      public Builder mergeFuelIndex(com.google.protobuf.Int32Value value) {
        if (fuelIndexBuilder_ == null) {
          if (fuelCase_ == 3 &&
              fuel_ != com.google.protobuf.Int32Value.getDefaultInstance()) {
            fuel_ = com.google.protobuf.Int32Value.newBuilder((com.google.protobuf.Int32Value) fuel_)
                .mergeFrom(value).buildPartial();
          } else {
            fuel_ = value;
          }
          onChanged();
        } else {
          if (fuelCase_ == 3) {
            fuelIndexBuilder_.mergeFrom(value);
          }
          fuelIndexBuilder_.setMessage(value);
        }
        fuelCase_ = 3;
        return this;
      }
      /**
       * <code>.google.protobuf.Int32Value fuelIndex = 3;</code>
       */
      public Builder clearFuelIndex() {
        if (fuelIndexBuilder_ == null) {
          if (fuelCase_ == 3) {
            fuelCase_ = 0;
            fuel_ = null;
            onChanged();
          }
        } else {
          if (fuelCase_ == 3) {
            fuelCase_ = 0;
            fuel_ = null;
          }
          fuelIndexBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Int32Value fuelIndex = 3;</code>
       */
      public com.google.protobuf.Int32Value.Builder getFuelIndexBuilder() {
        return getFuelIndexFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Int32Value fuelIndex = 3;</code>
       */
      @java.lang.Override
      public com.google.protobuf.Int32ValueOrBuilder getFuelIndexOrBuilder() {
        if ((fuelCase_ == 3) && (fuelIndexBuilder_ != null)) {
          return fuelIndexBuilder_.getMessageOrBuilder();
        } else {
          if (fuelCase_ == 3) {
            return (com.google.protobuf.Int32Value) fuel_;
          }
          return com.google.protobuf.Int32Value.getDefaultInstance();
        }
      }
      /**
       * <code>.google.protobuf.Int32Value fuelIndex = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
          getFuelIndexFieldBuilder() {
        if (fuelIndexBuilder_ == null) {
          if (!(fuelCase_ == 3)) {
            fuel_ = com.google.protobuf.Int32Value.getDefaultInstance();
          }
          fuelIndexBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                  (com.google.protobuf.Int32Value) fuel_,
                  getParentForChildren(),
                  isClean());
          fuel_ = null;
        }
        fuelCase_ = 3;
        onChanged();;
        return fuelIndexBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          ca.wise.fuel.proto.CcwfgmFuel, ca.wise.fuel.proto.CcwfgmFuel.Builder, ca.wise.fuel.proto.CcwfgmFuelOrBuilder> fuelDataBuilder_;
      /**
       * <code>.WISE.FuelProto.CcwfgmFuel fuelData = 4;</code>
       * @return Whether the fuelData field is set.
       */
      @java.lang.Override
      public boolean hasFuelData() {
        return fuelCase_ == 4;
      }
      /**
       * <code>.WISE.FuelProto.CcwfgmFuel fuelData = 4;</code>
       * @return The fuelData.
       */
      @java.lang.Override
      public ca.wise.fuel.proto.CcwfgmFuel getFuelData() {
        if (fuelDataBuilder_ == null) {
          if (fuelCase_ == 4) {
            return (ca.wise.fuel.proto.CcwfgmFuel) fuel_;
          }
          return ca.wise.fuel.proto.CcwfgmFuel.getDefaultInstance();
        } else {
          if (fuelCase_ == 4) {
            return fuelDataBuilder_.getMessage();
          }
          return ca.wise.fuel.proto.CcwfgmFuel.getDefaultInstance();
        }
      }
      /**
       * <code>.WISE.FuelProto.CcwfgmFuel fuelData = 4;</code>
       */
      public Builder setFuelData(ca.wise.fuel.proto.CcwfgmFuel value) {
        if (fuelDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fuel_ = value;
          onChanged();
        } else {
          fuelDataBuilder_.setMessage(value);
        }
        fuelCase_ = 4;
        return this;
      }
      /**
       * <code>.WISE.FuelProto.CcwfgmFuel fuelData = 4;</code>
       */
      public Builder setFuelData(
          ca.wise.fuel.proto.CcwfgmFuel.Builder builderForValue) {
        if (fuelDataBuilder_ == null) {
          fuel_ = builderForValue.build();
          onChanged();
        } else {
          fuelDataBuilder_.setMessage(builderForValue.build());
        }
        fuelCase_ = 4;
        return this;
      }
      /**
       * <code>.WISE.FuelProto.CcwfgmFuel fuelData = 4;</code>
       */
      public Builder mergeFuelData(ca.wise.fuel.proto.CcwfgmFuel value) {
        if (fuelDataBuilder_ == null) {
          if (fuelCase_ == 4 &&
              fuel_ != ca.wise.fuel.proto.CcwfgmFuel.getDefaultInstance()) {
            fuel_ = ca.wise.fuel.proto.CcwfgmFuel.newBuilder((ca.wise.fuel.proto.CcwfgmFuel) fuel_)
                .mergeFrom(value).buildPartial();
          } else {
            fuel_ = value;
          }
          onChanged();
        } else {
          if (fuelCase_ == 4) {
            fuelDataBuilder_.mergeFrom(value);
          }
          fuelDataBuilder_.setMessage(value);
        }
        fuelCase_ = 4;
        return this;
      }
      /**
       * <code>.WISE.FuelProto.CcwfgmFuel fuelData = 4;</code>
       */
      public Builder clearFuelData() {
        if (fuelDataBuilder_ == null) {
          if (fuelCase_ == 4) {
            fuelCase_ = 0;
            fuel_ = null;
            onChanged();
          }
        } else {
          if (fuelCase_ == 4) {
            fuelCase_ = 0;
            fuel_ = null;
          }
          fuelDataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.WISE.FuelProto.CcwfgmFuel fuelData = 4;</code>
       */
      public ca.wise.fuel.proto.CcwfgmFuel.Builder getFuelDataBuilder() {
        return getFuelDataFieldBuilder().getBuilder();
      }
      /**
       * <code>.WISE.FuelProto.CcwfgmFuel fuelData = 4;</code>
       */
      @java.lang.Override
      public ca.wise.fuel.proto.CcwfgmFuelOrBuilder getFuelDataOrBuilder() {
        if ((fuelCase_ == 4) && (fuelDataBuilder_ != null)) {
          return fuelDataBuilder_.getMessageOrBuilder();
        } else {
          if (fuelCase_ == 4) {
            return (ca.wise.fuel.proto.CcwfgmFuel) fuel_;
          }
          return ca.wise.fuel.proto.CcwfgmFuel.getDefaultInstance();
        }
      }
      /**
       * <code>.WISE.FuelProto.CcwfgmFuel fuelData = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.wise.fuel.proto.CcwfgmFuel, ca.wise.fuel.proto.CcwfgmFuel.Builder, ca.wise.fuel.proto.CcwfgmFuelOrBuilder> 
          getFuelDataFieldBuilder() {
        if (fuelDataBuilder_ == null) {
          if (!(fuelCase_ == 4)) {
            fuel_ = ca.wise.fuel.proto.CcwfgmFuel.getDefaultInstance();
          }
          fuelDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ca.wise.fuel.proto.CcwfgmFuel, ca.wise.fuel.proto.CcwfgmFuel.Builder, ca.wise.fuel.proto.CcwfgmFuelOrBuilder>(
                  (ca.wise.fuel.proto.CcwfgmFuel) fuel_,
                  getParentForChildren(),
                  isClean());
          fuel_ = null;
        }
        fuelCase_ = 4;
        onChanged();;
        return fuelDataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:WISE.GridProto.CwfgmFuelMap.CwfgmFuelData)
    }

    // @@protoc_insertion_point(class_scope:WISE.GridProto.CwfgmFuelMap.CwfgmFuelData)
    private static final ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData();
    }

    public static ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CwfgmFuelData>
        PARSER = new com.google.protobuf.AbstractParser<CwfgmFuelData>() {
      @java.lang.Override
      public CwfgmFuelData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CwfgmFuelData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CwfgmFuelData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CwfgmFuelData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int DATA_FIELD_NUMBER = 2;
  private java.util.List<ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData> data_;
  /**
   * <code>repeated .WISE.GridProto.CwfgmFuelMap.CwfgmFuelData data = 2;</code>
   */
  @java.lang.Override
  public java.util.List<ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData> getDataList() {
    return data_;
  }
  /**
   * <code>repeated .WISE.GridProto.CwfgmFuelMap.CwfgmFuelData data = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelDataOrBuilder> 
      getDataOrBuilderList() {
    return data_;
  }
  /**
   * <code>repeated .WISE.GridProto.CwfgmFuelMap.CwfgmFuelData data = 2;</code>
   */
  @java.lang.Override
  public int getDataCount() {
    return data_.size();
  }
  /**
   * <code>repeated .WISE.GridProto.CwfgmFuelMap.CwfgmFuelData data = 2;</code>
   */
  @java.lang.Override
  public ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData getData(int index) {
    return data_.get(index);
  }
  /**
   * <code>repeated .WISE.GridProto.CwfgmFuelMap.CwfgmFuelData data = 2;</code>
   */
  @java.lang.Override
  public ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelDataOrBuilder getDataOrBuilder(
      int index) {
    return data_.get(index);
  }

  public static final int IMPORTEDLUT_FIELD_NUMBER = 3;
  private boolean importedLut_;
  /**
   * <code>bool importedLut = 3;</code>
   * @return Whether the importedLut field is set.
   */
  @java.lang.Override
  public boolean hasImportedLut() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>bool importedLut = 3;</code>
   * @return The importedLut.
   */
  @java.lang.Override
  public boolean getImportedLut() {
    return importedLut_;
  }

  public static final int LUTFILENAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object lutFilename_;
  /**
   * <code>string lutFilename = 4;</code>
   * @return Whether the lutFilename field is set.
   */
  @java.lang.Override
  public boolean hasLutFilename() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>string lutFilename = 4;</code>
   * @return The lutFilename.
   */
  @java.lang.Override
  public java.lang.String getLutFilename() {
    java.lang.Object ref = lutFilename_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lutFilename_ = s;
      return s;
    }
  }
  /**
   * <code>string lutFilename = 4;</code>
   * @return The bytes for lutFilename.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLutFilenameBytes() {
    java.lang.Object ref = lutFilename_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lutFilename_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SHOWUNUSED_FIELD_NUMBER = 5;
  private boolean showUnused_;
  /**
   * <code>bool showUnused = 5;</code>
   * @return Whether the showUnused field is set.
   */
  @java.lang.Override
  public boolean hasShowUnused() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>bool showUnused = 5;</code>
   * @return The showUnused.
   */
  @java.lang.Override
  public boolean getShowUnused() {
    return showUnused_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0) {
      output.writeInt32(1, version_);
    }
    for (int i = 0; i < data_.size(); i++) {
      output.writeMessage(2, data_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBool(3, importedLut_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, lutFilename_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeBool(5, showUnused_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, version_);
    }
    for (int i = 0; i < data_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, data_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, importedLut_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, lutFilename_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, showUnused_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.wise.grid.proto.CwfgmFuelMap)) {
      return super.equals(obj);
    }
    ca.wise.grid.proto.CwfgmFuelMap other = (ca.wise.grid.proto.CwfgmFuelMap) obj;

    if (getVersion()
        != other.getVersion()) return false;
    if (!getDataList()
        .equals(other.getDataList())) return false;
    if (hasImportedLut() != other.hasImportedLut()) return false;
    if (hasImportedLut()) {
      if (getImportedLut()
          != other.getImportedLut()) return false;
    }
    if (hasLutFilename() != other.hasLutFilename()) return false;
    if (hasLutFilename()) {
      if (!getLutFilename()
          .equals(other.getLutFilename())) return false;
    }
    if (hasShowUnused() != other.hasShowUnused()) return false;
    if (hasShowUnused()) {
      if (getShowUnused()
          != other.getShowUnused()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    if (getDataCount() > 0) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getDataList().hashCode();
    }
    if (hasImportedLut()) {
      hash = (37 * hash) + IMPORTEDLUT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getImportedLut());
    }
    if (hasLutFilename()) {
      hash = (37 * hash) + LUTFILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getLutFilename().hashCode();
    }
    if (hasShowUnused()) {
      hash = (37 * hash) + SHOWUNUSED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getShowUnused());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.wise.grid.proto.CwfgmFuelMap parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.grid.proto.CwfgmFuelMap parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.grid.proto.CwfgmFuelMap parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.grid.proto.CwfgmFuelMap parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.grid.proto.CwfgmFuelMap parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.grid.proto.CwfgmFuelMap parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.grid.proto.CwfgmFuelMap parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.grid.proto.CwfgmFuelMap parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.grid.proto.CwfgmFuelMap parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.wise.grid.proto.CwfgmFuelMap parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.grid.proto.CwfgmFuelMap parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.grid.proto.CwfgmFuelMap parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.wise.grid.proto.CwfgmFuelMap prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WISE.GridProto.CwfgmFuelMap}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WISE.GridProto.CwfgmFuelMap)
      ca.wise.grid.proto.CwfgmFuelMapOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.grid.proto.CwfgmFuelMapOuterClass.internal_static_WISE_GridProto_CwfgmFuelMap_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.grid.proto.CwfgmFuelMapOuterClass.internal_static_WISE_GridProto_CwfgmFuelMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.grid.proto.CwfgmFuelMap.class, ca.wise.grid.proto.CwfgmFuelMap.Builder.class);
    }

    // Construct using ca.wise.grid.proto.CwfgmFuelMap.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDataFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = 0;

      if (dataBuilder_ == null) {
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        dataBuilder_.clear();
      }
      importedLut_ = false;
      bitField0_ = (bitField0_ & ~0x00000002);
      lutFilename_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      showUnused_ = false;
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.wise.grid.proto.CwfgmFuelMapOuterClass.internal_static_WISE_GridProto_CwfgmFuelMap_descriptor;
    }

    @java.lang.Override
    public ca.wise.grid.proto.CwfgmFuelMap getDefaultInstanceForType() {
      return ca.wise.grid.proto.CwfgmFuelMap.getDefaultInstance();
    }

    @java.lang.Override
    public ca.wise.grid.proto.CwfgmFuelMap build() {
      ca.wise.grid.proto.CwfgmFuelMap result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.wise.grid.proto.CwfgmFuelMap buildPartial() {
      ca.wise.grid.proto.CwfgmFuelMap result = new ca.wise.grid.proto.CwfgmFuelMap(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.version_ = version_;
      if (dataBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          data_ = java.util.Collections.unmodifiableList(data_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.data_ = data_;
      } else {
        result.data_ = dataBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.importedLut_ = importedLut_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.lutFilename_ = lutFilename_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.showUnused_ = showUnused_;
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.wise.grid.proto.CwfgmFuelMap) {
        return mergeFrom((ca.wise.grid.proto.CwfgmFuelMap)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.wise.grid.proto.CwfgmFuelMap other) {
      if (other == ca.wise.grid.proto.CwfgmFuelMap.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (dataBuilder_ == null) {
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
      } else {
        if (!other.data_.isEmpty()) {
          if (dataBuilder_.isEmpty()) {
            dataBuilder_.dispose();
            dataBuilder_ = null;
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000001);
            dataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDataFieldBuilder() : null;
          } else {
            dataBuilder_.addAllMessages(other.data_);
          }
        }
      }
      if (other.hasImportedLut()) {
        setImportedLut(other.getImportedLut());
      }
      if (other.hasLutFilename()) {
        bitField0_ |= 0x00000004;
        lutFilename_ = other.lutFilename_;
        onChanged();
      }
      if (other.hasShowUnused()) {
        setShowUnused(other.getShowUnused());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.wise.grid.proto.CwfgmFuelMap parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.wise.grid.proto.CwfgmFuelMap) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int version_ ;
    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <code>int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData> data_ =
      java.util.Collections.emptyList();
    private void ensureDataIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        data_ = new java.util.ArrayList<ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData>(data_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData, ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData.Builder, ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelDataOrBuilder> dataBuilder_;

    /**
     * <code>repeated .WISE.GridProto.CwfgmFuelMap.CwfgmFuelData data = 2;</code>
     */
    public java.util.List<ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData> getDataList() {
      if (dataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(data_);
      } else {
        return dataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmFuelMap.CwfgmFuelData data = 2;</code>
     */
    public int getDataCount() {
      if (dataBuilder_ == null) {
        return data_.size();
      } else {
        return dataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmFuelMap.CwfgmFuelData data = 2;</code>
     */
    public ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData getData(int index) {
      if (dataBuilder_ == null) {
        return data_.get(index);
      } else {
        return dataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmFuelMap.CwfgmFuelData data = 2;</code>
     */
    public Builder setData(
        int index, ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.set(index, value);
        onChanged();
      } else {
        dataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmFuelMap.CwfgmFuelData data = 2;</code>
     */
    public Builder setData(
        int index, ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.set(index, builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmFuelMap.CwfgmFuelData data = 2;</code>
     */
    public Builder addData(ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.add(value);
        onChanged();
      } else {
        dataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmFuelMap.CwfgmFuelData data = 2;</code>
     */
    public Builder addData(
        int index, ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.add(index, value);
        onChanged();
      } else {
        dataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmFuelMap.CwfgmFuelData data = 2;</code>
     */
    public Builder addData(
        ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.add(builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmFuelMap.CwfgmFuelData data = 2;</code>
     */
    public Builder addData(
        int index, ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.add(index, builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmFuelMap.CwfgmFuelData data = 2;</code>
     */
    public Builder addAllData(
        java.lang.Iterable<? extends ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData> values) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, data_);
        onChanged();
      } else {
        dataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmFuelMap.CwfgmFuelData data = 2;</code>
     */
    public Builder clearData() {
      if (dataBuilder_ == null) {
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        dataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmFuelMap.CwfgmFuelData data = 2;</code>
     */
    public Builder removeData(int index) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.remove(index);
        onChanged();
      } else {
        dataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmFuelMap.CwfgmFuelData data = 2;</code>
     */
    public ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData.Builder getDataBuilder(
        int index) {
      return getDataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmFuelMap.CwfgmFuelData data = 2;</code>
     */
    public ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelDataOrBuilder getDataOrBuilder(
        int index) {
      if (dataBuilder_ == null) {
        return data_.get(index);  } else {
        return dataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmFuelMap.CwfgmFuelData data = 2;</code>
     */
    public java.util.List<? extends ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelDataOrBuilder> 
         getDataOrBuilderList() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(data_);
      }
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmFuelMap.CwfgmFuelData data = 2;</code>
     */
    public ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData.Builder addDataBuilder() {
      return getDataFieldBuilder().addBuilder(
          ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData.getDefaultInstance());
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmFuelMap.CwfgmFuelData data = 2;</code>
     */
    public ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData.Builder addDataBuilder(
        int index) {
      return getDataFieldBuilder().addBuilder(
          index, ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData.getDefaultInstance());
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmFuelMap.CwfgmFuelData data = 2;</code>
     */
    public java.util.List<ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData.Builder> 
         getDataBuilderList() {
      return getDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData, ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData.Builder, ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelDataOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData, ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData.Builder, ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelDataOrBuilder>(
                data_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }

    private boolean importedLut_ ;
    /**
     * <code>bool importedLut = 3;</code>
     * @return Whether the importedLut field is set.
     */
    @java.lang.Override
    public boolean hasImportedLut() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>bool importedLut = 3;</code>
     * @return The importedLut.
     */
    @java.lang.Override
    public boolean getImportedLut() {
      return importedLut_;
    }
    /**
     * <code>bool importedLut = 3;</code>
     * @param value The importedLut to set.
     * @return This builder for chaining.
     */
    public Builder setImportedLut(boolean value) {
      bitField0_ |= 0x00000002;
      importedLut_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool importedLut = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearImportedLut() {
      bitField0_ = (bitField0_ & ~0x00000002);
      importedLut_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object lutFilename_ = "";
    /**
     * <code>string lutFilename = 4;</code>
     * @return Whether the lutFilename field is set.
     */
    public boolean hasLutFilename() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>string lutFilename = 4;</code>
     * @return The lutFilename.
     */
    public java.lang.String getLutFilename() {
      java.lang.Object ref = lutFilename_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lutFilename_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string lutFilename = 4;</code>
     * @return The bytes for lutFilename.
     */
    public com.google.protobuf.ByteString
        getLutFilenameBytes() {
      java.lang.Object ref = lutFilename_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lutFilename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lutFilename = 4;</code>
     * @param value The lutFilename to set.
     * @return This builder for chaining.
     */
    public Builder setLutFilename(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      lutFilename_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string lutFilename = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLutFilename() {
      bitField0_ = (bitField0_ & ~0x00000004);
      lutFilename_ = getDefaultInstance().getLutFilename();
      onChanged();
      return this;
    }
    /**
     * <code>string lutFilename = 4;</code>
     * @param value The bytes for lutFilename to set.
     * @return This builder for chaining.
     */
    public Builder setLutFilenameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000004;
      lutFilename_ = value;
      onChanged();
      return this;
    }

    private boolean showUnused_ ;
    /**
     * <code>bool showUnused = 5;</code>
     * @return Whether the showUnused field is set.
     */
    @java.lang.Override
    public boolean hasShowUnused() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>bool showUnused = 5;</code>
     * @return The showUnused.
     */
    @java.lang.Override
    public boolean getShowUnused() {
      return showUnused_;
    }
    /**
     * <code>bool showUnused = 5;</code>
     * @param value The showUnused to set.
     * @return This builder for chaining.
     */
    public Builder setShowUnused(boolean value) {
      bitField0_ |= 0x00000008;
      showUnused_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool showUnused = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearShowUnused() {
      bitField0_ = (bitField0_ & ~0x00000008);
      showUnused_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WISE.GridProto.CwfgmFuelMap)
  }

  // @@protoc_insertion_point(class_scope:WISE.GridProto.CwfgmFuelMap)
  private static final ca.wise.grid.proto.CwfgmFuelMap DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.wise.grid.proto.CwfgmFuelMap();
  }

  public static ca.wise.grid.proto.CwfgmFuelMap getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CwfgmFuelMap>
      PARSER = new com.google.protobuf.AbstractParser<CwfgmFuelMap>() {
    @java.lang.Override
    public CwfgmFuelMap parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CwfgmFuelMap(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CwfgmFuelMap> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CwfgmFuelMap> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.wise.grid.proto.CwfgmFuelMap getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

