// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cwfgmFuelMap.proto

package ca.wise.grid.proto;

public interface CwfgmFuelMapOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.GridProto.CwfgmFuelMap)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>repeated .WISE.GridProto.CwfgmFuelMap.CwfgmFuelData data = 2;</code>
   */
  java.util.List<ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData> 
      getDataList();
  /**
   * <code>repeated .WISE.GridProto.CwfgmFuelMap.CwfgmFuelData data = 2;</code>
   */
  ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelData getData(int index);
  /**
   * <code>repeated .WISE.GridProto.CwfgmFuelMap.CwfgmFuelData data = 2;</code>
   */
  int getDataCount();
  /**
   * <code>repeated .WISE.GridProto.CwfgmFuelMap.CwfgmFuelData data = 2;</code>
   */
  java.util.List<? extends ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelDataOrBuilder> 
      getDataOrBuilderList();
  /**
   * <code>repeated .WISE.GridProto.CwfgmFuelMap.CwfgmFuelData data = 2;</code>
   */
  ca.wise.grid.proto.CwfgmFuelMap.CwfgmFuelDataOrBuilder getDataOrBuilder(
      int index);

  /**
   * <code>bool importedLut = 3;</code>
   * @return Whether the importedLut field is set.
   */
  boolean hasImportedLut();
  /**
   * <code>bool importedLut = 3;</code>
   * @return The importedLut.
   */
  boolean getImportedLut();

  /**
   * <code>string lutFilename = 4;</code>
   * @return Whether the lutFilename field is set.
   */
  boolean hasLutFilename();
  /**
   * <code>string lutFilename = 4;</code>
   * @return The lutFilename.
   */
  java.lang.String getLutFilename();
  /**
   * <code>string lutFilename = 4;</code>
   * @return The bytes for lutFilename.
   */
  com.google.protobuf.ByteString
      getLutFilenameBytes();

  /**
   * <code>bool showUnused = 5;</code>
   * @return Whether the showUnused field is set.
   */
  boolean hasShowUnused();
  /**
   * <code>bool showUnused = 5;</code>
   * @return The showUnused.
   */
  boolean getShowUnused();
}
