// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cwfgmFilter.proto

package ca.wise.grid.proto;

public interface CwfgmPolyReplaceGridFilterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.GridProto.CwfgmPolyReplaceGridFilter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>.Geography.GeoPoly polygons = 2;</code>
   * @return Whether the polygons field is set.
   */
  boolean hasPolygons();
  /**
   * <code>.Geography.GeoPoly polygons = 2;</code>
   * @return The polygons.
   */
  ca.hss.math.proto.GeoPoly getPolygons();
  /**
   * <code>.Geography.GeoPoly polygons = 2;</code>
   */
  ca.hss.math.proto.GeoPolyOrBuilder getPolygonsOrBuilder();

  /**
   * <code>string filename = 3;</code>
   * @return The filename.
   */
  java.lang.String getFilename();
  /**
   * <code>string filename = 3;</code>
   * @return The bytes for filename.
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 4;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 4;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 4;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string comments = 5;</code>
   * @return Whether the comments field is set.
   */
  boolean hasComments();
  /**
   * <code>string comments = 5;</code>
   * @return The comments.
   */
  java.lang.String getComments();
  /**
   * <code>string comments = 5;</code>
   * @return The bytes for comments.
   */
  com.google.protobuf.ByteString
      getCommentsBytes();

  /**
   * <code>uint32 color = 6;</code>
   * @return Whether the color field is set.
   */
  boolean hasColor();
  /**
   * <code>uint32 color = 6;</code>
   * @return The color.
   */
  int getColor();

  /**
   * <code>uint64 size = 7;</code>
   * @return Whether the size field is set.
   */
  boolean hasSize();
  /**
   * <code>uint64 size = 7;</code>
   * @return The size.
   */
  long getSize();

  /**
   * <code>.WISE.GridProto.CwfgmReplaceGridFilterBase filter = 8;</code>
   * @return Whether the filter field is set.
   */
  boolean hasFilter();
  /**
   * <code>.WISE.GridProto.CwfgmReplaceGridFilterBase filter = 8;</code>
   * @return The filter.
   */
  ca.wise.grid.proto.CwfgmReplaceGridFilterBase getFilter();
  /**
   * <code>.WISE.GridProto.CwfgmReplaceGridFilterBase filter = 8;</code>
   */
  ca.wise.grid.proto.CwfgmReplaceGridFilterBaseOrBuilder getFilterOrBuilder();

  public ca.wise.grid.proto.CwfgmPolyReplaceGridFilter.ShapeCase getShapeCase();
}
