// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cwfgmFilter.proto

package ca.wise.grid.proto;

public interface CwfgmReplaceGridFilterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.GridProto.CwfgmReplaceGridFilter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>.Geography.GeoPoint pointOne = 2;</code>
   * @return Whether the pointOne field is set.
   */
  boolean hasPointOne();
  /**
   * <code>.Geography.GeoPoint pointOne = 2;</code>
   * @return The pointOne.
   */
  ca.hss.math.proto.GeoPoint getPointOne();
  /**
   * <code>.Geography.GeoPoint pointOne = 2;</code>
   */
  ca.hss.math.proto.GeoPointOrBuilder getPointOneOrBuilder();

  /**
   * <code>.Geography.GeoPoint pointTwo = 3;</code>
   * @return Whether the pointTwo field is set.
   */
  boolean hasPointTwo();
  /**
   * <code>.Geography.GeoPoint pointTwo = 3;</code>
   * @return The pointTwo.
   */
  ca.hss.math.proto.GeoPoint getPointTwo();
  /**
   * <code>.Geography.GeoPoint pointTwo = 3;</code>
   */
  ca.hss.math.proto.GeoPointOrBuilder getPointTwoOrBuilder();

  /**
   * <code>.Math.Double xLLCorner = 4;</code>
   * @return Whether the xLLCorner field is set.
   */
  boolean hasXLLCorner();
  /**
   * <code>.Math.Double xLLCorner = 4;</code>
   * @return The xLLCorner.
   */
  ca.hss.math.proto.Double getXLLCorner();
  /**
   * <code>.Math.Double xLLCorner = 4;</code>
   */
  ca.hss.math.proto.DoubleOrBuilder getXLLCornerOrBuilder();

  /**
   * <code>.Math.Double yLLCorner = 5;</code>
   * @return Whether the yLLCorner field is set.
   */
  boolean hasYLLCorner();
  /**
   * <code>.Math.Double yLLCorner = 5;</code>
   * @return The yLLCorner.
   */
  ca.hss.math.proto.Double getYLLCorner();
  /**
   * <code>.Math.Double yLLCorner = 5;</code>
   */
  ca.hss.math.proto.DoubleOrBuilder getYLLCornerOrBuilder();

  /**
   * <code>.Math.Double resolution = 6;</code>
   * @return Whether the resolution field is set.
   */
  boolean hasResolution();
  /**
   * <code>.Math.Double resolution = 6;</code>
   * @return The resolution.
   */
  ca.hss.math.proto.Double getResolution();
  /**
   * <code>.Math.Double resolution = 6;</code>
   */
  ca.hss.math.proto.DoubleOrBuilder getResolutionOrBuilder();

  /**
   * <code>.google.protobuf.BoolValue landscape = 7;</code>
   * @return Whether the landscape field is set.
   */
  boolean hasLandscape();
  /**
   * <code>.google.protobuf.BoolValue landscape = 7;</code>
   * @return The landscape.
   */
  com.google.protobuf.BoolValue getLandscape();
  /**
   * <code>.google.protobuf.BoolValue landscape = 7;</code>
   */
  com.google.protobuf.BoolValueOrBuilder getLandscapeOrBuilder();

  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 8;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 8;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 8;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string comments = 9;</code>
   * @return Whether the comments field is set.
   */
  boolean hasComments();
  /**
   * <code>string comments = 9;</code>
   * @return The comments.
   */
  java.lang.String getComments();
  /**
   * <code>string comments = 9;</code>
   * @return The bytes for comments.
   */
  com.google.protobuf.ByteString
      getCommentsBytes();

  /**
   * <code>.WISE.GridProto.CwfgmReplaceGridFilterBase filter = 10;</code>
   * @return Whether the filter field is set.
   */
  boolean hasFilter();
  /**
   * <code>.WISE.GridProto.CwfgmReplaceGridFilterBase filter = 10;</code>
   * @return The filter.
   */
  ca.wise.grid.proto.CwfgmReplaceGridFilterBase getFilter();
  /**
   * <code>.WISE.GridProto.CwfgmReplaceGridFilterBase filter = 10;</code>
   */
  ca.wise.grid.proto.CwfgmReplaceGridFilterBaseOrBuilder getFilterOrBuilder();
}
