// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cwfgmFuelMap.proto

package ca.wise.grid.proto;

public final class CwfgmFuelMapOuterClass {
  private CwfgmFuelMapOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_GridProto_CwfgmFuelMap_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_GridProto_CwfgmFuelMap_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_GridProto_CwfgmFuelMap_CwfgmFuelData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_GridProto_CwfgmFuelMap_CwfgmFuelData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022cwfgmFuelMap.proto\022\016WISE.GridProto\032\020cc" +
      "wfgmFuel.proto\032\036google/protobuf/wrappers" +
      ".proto\"\365\002\n\014CwfgmFuelMap\022\017\n\007version\030\001 \001(\005" +
      "\0228\n\004data\030\002 \003(\0132*.WISE.GridProto.CwfgmFue" +
      "lMap.CwfgmFuelData\022\030\n\013importedLut\030\003 \001(\010H" +
      "\000\210\001\001\022\030\n\013lutFilename\030\004 \001(\tH\001\210\001\001\022\027\n\nshowUn" +
      "used\030\005 \001(\010H\002\210\001\001\032\235\001\n\rCwfgmFuelData\022\r\n\005ind" +
      "ex\030\001 \001(\005\022\023\n\013exportIndex\030\002 \001(\005\0220\n\tfuelInd" +
      "ex\030\003 \001(\0132\033.google.protobuf.Int32ValueH\000\022" +
      ".\n\010fuelData\030\004 \001(\0132\032.WISE.FuelProto.Ccwfg" +
      "mFuelH\000B\006\n\004fuelB\016\n\014_importedLutB\016\n\014_lutF" +
      "ilenameB\r\n\013_showUnusedB\'\n\022ca.wise.grid.p" +
      "rotoP\001\252\002\016WISE.GridProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ca.wise.fuel.proto.CcwfgmFuelOuterClass.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_WISE_GridProto_CwfgmFuelMap_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WISE_GridProto_CwfgmFuelMap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_GridProto_CwfgmFuelMap_descriptor,
        new java.lang.String[] { "Version", "Data", "ImportedLut", "LutFilename", "ShowUnused", "ImportedLut", "LutFilename", "ShowUnused", });
    internal_static_WISE_GridProto_CwfgmFuelMap_CwfgmFuelData_descriptor =
      internal_static_WISE_GridProto_CwfgmFuelMap_descriptor.getNestedTypes().get(0);
    internal_static_WISE_GridProto_CwfgmFuelMap_CwfgmFuelData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_GridProto_CwfgmFuelMap_CwfgmFuelData_descriptor,
        new java.lang.String[] { "Index", "ExportIndex", "FuelIndex", "FuelData", "Fuel", });
    ca.wise.fuel.proto.CcwfgmFuelOuterClass.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
