// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cwfgmFilter.proto

package ca.wise.grid.proto;

/**
 * Protobuf type {@code WISE.GridProto.CwfgmTarget}
 */
public final class CwfgmTarget extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WISE.GridProto.CwfgmTarget)
    CwfgmTargetOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CwfgmTarget.newBuilder() to construct.
  private CwfgmTarget(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CwfgmTarget() {
    name_ = "";
    comments_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CwfgmTarget();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CwfgmTarget(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            version_ = input.readInt32();
            break;
          }
          case 18: {
            ca.hss.math.proto.GeoPoly.Builder subBuilder = null;
            if (dataCase_ == 2) {
              subBuilder = ((ca.hss.math.proto.GeoPoly) data_).toBuilder();
            }
            data_ =
                input.readMessage(ca.hss.math.proto.GeoPoly.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ca.hss.math.proto.GeoPoly) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 2;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            dataCase_ = 3;
            data_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            name_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000002;
            comments_ = s;
            break;
          }
          case 48: {
            bitField0_ |= 0x00000004;
            color_ = input.readUInt32();
            break;
          }
          case 56: {
            bitField0_ |= 0x00000008;
            symbol_ = input.readUInt64();
            break;
          }
          case 64: {
            bitField0_ |= 0x00000010;
            displaySize_ = input.readSInt32();
            break;
          }
          case 72: {
            bitField0_ |= 0x00000020;
            imported_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.wise.grid.proto.CwfgmFilter.internal_static_WISE_GridProto_CwfgmTarget_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.wise.grid.proto.CwfgmFilter.internal_static_WISE_GridProto_CwfgmTarget_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.wise.grid.proto.CwfgmTarget.class, ca.wise.grid.proto.CwfgmTarget.Builder.class);
  }

  private int bitField0_;
  private int dataCase_ = 0;
  private java.lang.Object data_;
  public enum DataCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    TARGETS(2),
    FILENAME(3),
    DATA_NOT_SET(0);
    private final int value;
    private DataCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataCase valueOf(int value) {
      return forNumber(value);
    }

    public static DataCase forNumber(int value) {
      switch (value) {
        case 2: return TARGETS;
        case 3: return FILENAME;
        case 0: return DATA_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public DataCase
  getDataCase() {
    return DataCase.forNumber(
        dataCase_);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int TARGETS_FIELD_NUMBER = 2;
  /**
   * <code>.Geography.GeoPoly targets = 2;</code>
   * @return Whether the targets field is set.
   */
  @java.lang.Override
  public boolean hasTargets() {
    return dataCase_ == 2;
  }
  /**
   * <code>.Geography.GeoPoly targets = 2;</code>
   * @return The targets.
   */
  @java.lang.Override
  public ca.hss.math.proto.GeoPoly getTargets() {
    if (dataCase_ == 2) {
       return (ca.hss.math.proto.GeoPoly) data_;
    }
    return ca.hss.math.proto.GeoPoly.getDefaultInstance();
  }
  /**
   * <code>.Geography.GeoPoly targets = 2;</code>
   */
  @java.lang.Override
  public ca.hss.math.proto.GeoPolyOrBuilder getTargetsOrBuilder() {
    if (dataCase_ == 2) {
       return (ca.hss.math.proto.GeoPoly) data_;
    }
    return ca.hss.math.proto.GeoPoly.getDefaultInstance();
  }

  public static final int FILENAME_FIELD_NUMBER = 3;
  /**
   * <code>string filename = 3;</code>
   * @return The filename.
   */
  public java.lang.String getFilename() {
    java.lang.Object ref = "";
    if (dataCase_ == 3) {
      ref = data_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (dataCase_ == 3) {
        data_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string filename = 3;</code>
   * @return The bytes for filename.
   */
  public com.google.protobuf.ByteString
      getFilenameBytes() {
    java.lang.Object ref = "";
    if (dataCase_ == 3) {
      ref = data_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (dataCase_ == 3) {
        data_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 4;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 4;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 4;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMENTS_FIELD_NUMBER = 5;
  private volatile java.lang.Object comments_;
  /**
   * <code>string comments = 5;</code>
   * @return Whether the comments field is set.
   */
  @java.lang.Override
  public boolean hasComments() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>string comments = 5;</code>
   * @return The comments.
   */
  @java.lang.Override
  public java.lang.String getComments() {
    java.lang.Object ref = comments_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      comments_ = s;
      return s;
    }
  }
  /**
   * <code>string comments = 5;</code>
   * @return The bytes for comments.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCommentsBytes() {
    java.lang.Object ref = comments_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      comments_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COLOR_FIELD_NUMBER = 6;
  private int color_;
  /**
   * <code>uint32 color = 6;</code>
   * @return Whether the color field is set.
   */
  @java.lang.Override
  public boolean hasColor() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>uint32 color = 6;</code>
   * @return The color.
   */
  @java.lang.Override
  public int getColor() {
    return color_;
  }

  public static final int SYMBOL_FIELD_NUMBER = 7;
  private long symbol_;
  /**
   * <code>uint64 symbol = 7;</code>
   * @return Whether the symbol field is set.
   */
  @java.lang.Override
  public boolean hasSymbol() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>uint64 symbol = 7;</code>
   * @return The symbol.
   */
  @java.lang.Override
  public long getSymbol() {
    return symbol_;
  }

  public static final int DISPLAYSIZE_FIELD_NUMBER = 8;
  private int displaySize_;
  /**
   * <code>sint32 displaySize = 8;</code>
   * @return Whether the displaySize field is set.
   */
  @java.lang.Override
  public boolean hasDisplaySize() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>sint32 displaySize = 8;</code>
   * @return The displaySize.
   */
  @java.lang.Override
  public int getDisplaySize() {
    return displaySize_;
  }

  public static final int IMPORTED_FIELD_NUMBER = 9;
  private boolean imported_;
  /**
   * <code>bool imported = 9;</code>
   * @return Whether the imported field is set.
   */
  @java.lang.Override
  public boolean hasImported() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>bool imported = 9;</code>
   * @return The imported.
   */
  @java.lang.Override
  public boolean getImported() {
    return imported_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0) {
      output.writeInt32(1, version_);
    }
    if (dataCase_ == 2) {
      output.writeMessage(2, (ca.hss.math.proto.GeoPoly) data_);
    }
    if (dataCase_ == 3) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, data_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, name_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, comments_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeUInt32(6, color_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeUInt64(7, symbol_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeSInt32(8, displaySize_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeBool(9, imported_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, version_);
    }
    if (dataCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (ca.hss.math.proto.GeoPoly) data_);
    }
    if (dataCase_ == 3) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, data_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, name_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, comments_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, color_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(7, symbol_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(8, displaySize_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(9, imported_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.wise.grid.proto.CwfgmTarget)) {
      return super.equals(obj);
    }
    ca.wise.grid.proto.CwfgmTarget other = (ca.wise.grid.proto.CwfgmTarget) obj;

    if (getVersion()
        != other.getVersion()) return false;
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasComments() != other.hasComments()) return false;
    if (hasComments()) {
      if (!getComments()
          .equals(other.getComments())) return false;
    }
    if (hasColor() != other.hasColor()) return false;
    if (hasColor()) {
      if (getColor()
          != other.getColor()) return false;
    }
    if (hasSymbol() != other.hasSymbol()) return false;
    if (hasSymbol()) {
      if (getSymbol()
          != other.getSymbol()) return false;
    }
    if (hasDisplaySize() != other.hasDisplaySize()) return false;
    if (hasDisplaySize()) {
      if (getDisplaySize()
          != other.getDisplaySize()) return false;
    }
    if (hasImported() != other.hasImported()) return false;
    if (hasImported()) {
      if (getImported()
          != other.getImported()) return false;
    }
    if (!getDataCase().equals(other.getDataCase())) return false;
    switch (dataCase_) {
      case 2:
        if (!getTargets()
            .equals(other.getTargets())) return false;
        break;
      case 3:
        if (!getFilename()
            .equals(other.getFilename())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasComments()) {
      hash = (37 * hash) + COMMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getComments().hashCode();
    }
    if (hasColor()) {
      hash = (37 * hash) + COLOR_FIELD_NUMBER;
      hash = (53 * hash) + getColor();
    }
    if (hasSymbol()) {
      hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSymbol());
    }
    if (hasDisplaySize()) {
      hash = (37 * hash) + DISPLAYSIZE_FIELD_NUMBER;
      hash = (53 * hash) + getDisplaySize();
    }
    if (hasImported()) {
      hash = (37 * hash) + IMPORTED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getImported());
    }
    switch (dataCase_) {
      case 2:
        hash = (37 * hash) + TARGETS_FIELD_NUMBER;
        hash = (53 * hash) + getTargets().hashCode();
        break;
      case 3:
        hash = (37 * hash) + FILENAME_FIELD_NUMBER;
        hash = (53 * hash) + getFilename().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.wise.grid.proto.CwfgmTarget parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.grid.proto.CwfgmTarget parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.grid.proto.CwfgmTarget parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.grid.proto.CwfgmTarget parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.grid.proto.CwfgmTarget parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.grid.proto.CwfgmTarget parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.grid.proto.CwfgmTarget parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.grid.proto.CwfgmTarget parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.grid.proto.CwfgmTarget parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.wise.grid.proto.CwfgmTarget parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.grid.proto.CwfgmTarget parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.grid.proto.CwfgmTarget parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.wise.grid.proto.CwfgmTarget prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WISE.GridProto.CwfgmTarget}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WISE.GridProto.CwfgmTarget)
      ca.wise.grid.proto.CwfgmTargetOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.grid.proto.CwfgmFilter.internal_static_WISE_GridProto_CwfgmTarget_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.grid.proto.CwfgmFilter.internal_static_WISE_GridProto_CwfgmTarget_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.grid.proto.CwfgmTarget.class, ca.wise.grid.proto.CwfgmTarget.Builder.class);
    }

    // Construct using ca.wise.grid.proto.CwfgmTarget.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = 0;

      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      comments_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      color_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      symbol_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000008);
      displaySize_ = 0;
      bitField0_ = (bitField0_ & ~0x00000010);
      imported_ = false;
      bitField0_ = (bitField0_ & ~0x00000020);
      dataCase_ = 0;
      data_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.wise.grid.proto.CwfgmFilter.internal_static_WISE_GridProto_CwfgmTarget_descriptor;
    }

    @java.lang.Override
    public ca.wise.grid.proto.CwfgmTarget getDefaultInstanceForType() {
      return ca.wise.grid.proto.CwfgmTarget.getDefaultInstance();
    }

    @java.lang.Override
    public ca.wise.grid.proto.CwfgmTarget build() {
      ca.wise.grid.proto.CwfgmTarget result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.wise.grid.proto.CwfgmTarget buildPartial() {
      ca.wise.grid.proto.CwfgmTarget result = new ca.wise.grid.proto.CwfgmTarget(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.version_ = version_;
      if (dataCase_ == 2) {
        if (targetsBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = targetsBuilder_.build();
        }
      }
      if (dataCase_ == 3) {
        result.data_ = data_;
      }
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.comments_ = comments_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.color_ = color_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.symbol_ = symbol_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.displaySize_ = displaySize_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.imported_ = imported_;
        to_bitField0_ |= 0x00000020;
      }
      result.bitField0_ = to_bitField0_;
      result.dataCase_ = dataCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.wise.grid.proto.CwfgmTarget) {
        return mergeFrom((ca.wise.grid.proto.CwfgmTarget)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.wise.grid.proto.CwfgmTarget other) {
      if (other == ca.wise.grid.proto.CwfgmTarget.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (other.hasName()) {
        bitField0_ |= 0x00000001;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasComments()) {
        bitField0_ |= 0x00000002;
        comments_ = other.comments_;
        onChanged();
      }
      if (other.hasColor()) {
        setColor(other.getColor());
      }
      if (other.hasSymbol()) {
        setSymbol(other.getSymbol());
      }
      if (other.hasDisplaySize()) {
        setDisplaySize(other.getDisplaySize());
      }
      if (other.hasImported()) {
        setImported(other.getImported());
      }
      switch (other.getDataCase()) {
        case TARGETS: {
          mergeTargets(other.getTargets());
          break;
        }
        case FILENAME: {
          dataCase_ = 3;
          data_ = other.data_;
          onChanged();
          break;
        }
        case DATA_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.wise.grid.proto.CwfgmTarget parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.wise.grid.proto.CwfgmTarget) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int dataCase_ = 0;
    private java.lang.Object data_;
    public DataCase
        getDataCase() {
      return DataCase.forNumber(
          dataCase_);
    }

    public Builder clearData() {
      dataCase_ = 0;
      data_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private int version_ ;
    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <code>int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.GeoPoly, ca.hss.math.proto.GeoPoly.Builder, ca.hss.math.proto.GeoPolyOrBuilder> targetsBuilder_;
    /**
     * <code>.Geography.GeoPoly targets = 2;</code>
     * @return Whether the targets field is set.
     */
    @java.lang.Override
    public boolean hasTargets() {
      return dataCase_ == 2;
    }
    /**
     * <code>.Geography.GeoPoly targets = 2;</code>
     * @return The targets.
     */
    @java.lang.Override
    public ca.hss.math.proto.GeoPoly getTargets() {
      if (targetsBuilder_ == null) {
        if (dataCase_ == 2) {
          return (ca.hss.math.proto.GeoPoly) data_;
        }
        return ca.hss.math.proto.GeoPoly.getDefaultInstance();
      } else {
        if (dataCase_ == 2) {
          return targetsBuilder_.getMessage();
        }
        return ca.hss.math.proto.GeoPoly.getDefaultInstance();
      }
    }
    /**
     * <code>.Geography.GeoPoly targets = 2;</code>
     */
    public Builder setTargets(ca.hss.math.proto.GeoPoly value) {
      if (targetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        targetsBuilder_.setMessage(value);
      }
      dataCase_ = 2;
      return this;
    }
    /**
     * <code>.Geography.GeoPoly targets = 2;</code>
     */
    public Builder setTargets(
        ca.hss.math.proto.GeoPoly.Builder builderForValue) {
      if (targetsBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        targetsBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 2;
      return this;
    }
    /**
     * <code>.Geography.GeoPoly targets = 2;</code>
     */
    public Builder mergeTargets(ca.hss.math.proto.GeoPoly value) {
      if (targetsBuilder_ == null) {
        if (dataCase_ == 2 &&
            data_ != ca.hss.math.proto.GeoPoly.getDefaultInstance()) {
          data_ = ca.hss.math.proto.GeoPoly.newBuilder((ca.hss.math.proto.GeoPoly) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 2) {
          targetsBuilder_.mergeFrom(value);
        }
        targetsBuilder_.setMessage(value);
      }
      dataCase_ = 2;
      return this;
    }
    /**
     * <code>.Geography.GeoPoly targets = 2;</code>
     */
    public Builder clearTargets() {
      if (targetsBuilder_ == null) {
        if (dataCase_ == 2) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 2) {
          dataCase_ = 0;
          data_ = null;
        }
        targetsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.Geography.GeoPoly targets = 2;</code>
     */
    public ca.hss.math.proto.GeoPoly.Builder getTargetsBuilder() {
      return getTargetsFieldBuilder().getBuilder();
    }
    /**
     * <code>.Geography.GeoPoly targets = 2;</code>
     */
    @java.lang.Override
    public ca.hss.math.proto.GeoPolyOrBuilder getTargetsOrBuilder() {
      if ((dataCase_ == 2) && (targetsBuilder_ != null)) {
        return targetsBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 2) {
          return (ca.hss.math.proto.GeoPoly) data_;
        }
        return ca.hss.math.proto.GeoPoly.getDefaultInstance();
      }
    }
    /**
     * <code>.Geography.GeoPoly targets = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.GeoPoly, ca.hss.math.proto.GeoPoly.Builder, ca.hss.math.proto.GeoPolyOrBuilder> 
        getTargetsFieldBuilder() {
      if (targetsBuilder_ == null) {
        if (!(dataCase_ == 2)) {
          data_ = ca.hss.math.proto.GeoPoly.getDefaultInstance();
        }
        targetsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.hss.math.proto.GeoPoly, ca.hss.math.proto.GeoPoly.Builder, ca.hss.math.proto.GeoPolyOrBuilder>(
                (ca.hss.math.proto.GeoPoly) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 2;
      onChanged();;
      return targetsBuilder_;
    }

    /**
     * <code>string filename = 3;</code>
     * @return The filename.
     */
    @java.lang.Override
    public java.lang.String getFilename() {
      java.lang.Object ref = "";
      if (dataCase_ == 3) {
        ref = data_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (dataCase_ == 3) {
          data_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string filename = 3;</code>
     * @return The bytes for filename.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      java.lang.Object ref = "";
      if (dataCase_ == 3) {
        ref = data_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (dataCase_ == 3) {
          data_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string filename = 3;</code>
     * @param value The filename to set.
     * @return This builder for chaining.
     */
    public Builder setFilename(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  dataCase_ = 3;
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string filename = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFilename() {
      if (dataCase_ == 3) {
        dataCase_ = 0;
        data_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string filename = 3;</code>
     * @param value The bytes for filename to set.
     * @return This builder for chaining.
     */
    public Builder setFilenameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      dataCase_ = 3;
      data_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * not really optional but need to be able to suppress it in the old file format
     * </pre>
     *
     * <code>string name = 4;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * not really optional but need to be able to suppress it in the old file format
     * </pre>
     *
     * <code>string name = 4;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * not really optional but need to be able to suppress it in the old file format
     * </pre>
     *
     * <code>string name = 4;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * not really optional but need to be able to suppress it in the old file format
     * </pre>
     *
     * <code>string name = 4;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * not really optional but need to be able to suppress it in the old file format
     * </pre>
     *
     * <code>string name = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * not really optional but need to be able to suppress it in the old file format
     * </pre>
     *
     * <code>string name = 4;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object comments_ = "";
    /**
     * <code>string comments = 5;</code>
     * @return Whether the comments field is set.
     */
    public boolean hasComments() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>string comments = 5;</code>
     * @return The comments.
     */
    public java.lang.String getComments() {
      java.lang.Object ref = comments_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        comments_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string comments = 5;</code>
     * @return The bytes for comments.
     */
    public com.google.protobuf.ByteString
        getCommentsBytes() {
      java.lang.Object ref = comments_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        comments_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string comments = 5;</code>
     * @param value The comments to set.
     * @return This builder for chaining.
     */
    public Builder setComments(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      comments_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string comments = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearComments() {
      bitField0_ = (bitField0_ & ~0x00000002);
      comments_ = getDefaultInstance().getComments();
      onChanged();
      return this;
    }
    /**
     * <code>string comments = 5;</code>
     * @param value The bytes for comments to set.
     * @return This builder for chaining.
     */
    public Builder setCommentsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      comments_ = value;
      onChanged();
      return this;
    }

    private int color_ ;
    /**
     * <code>uint32 color = 6;</code>
     * @return Whether the color field is set.
     */
    @java.lang.Override
    public boolean hasColor() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>uint32 color = 6;</code>
     * @return The color.
     */
    @java.lang.Override
    public int getColor() {
      return color_;
    }
    /**
     * <code>uint32 color = 6;</code>
     * @param value The color to set.
     * @return This builder for chaining.
     */
    public Builder setColor(int value) {
      bitField0_ |= 0x00000004;
      color_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 color = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearColor() {
      bitField0_ = (bitField0_ & ~0x00000004);
      color_ = 0;
      onChanged();
      return this;
    }

    private long symbol_ ;
    /**
     * <code>uint64 symbol = 7;</code>
     * @return Whether the symbol field is set.
     */
    @java.lang.Override
    public boolean hasSymbol() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>uint64 symbol = 7;</code>
     * @return The symbol.
     */
    @java.lang.Override
    public long getSymbol() {
      return symbol_;
    }
    /**
     * <code>uint64 symbol = 7;</code>
     * @param value The symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbol(long value) {
      bitField0_ |= 0x00000008;
      symbol_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 symbol = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSymbol() {
      bitField0_ = (bitField0_ & ~0x00000008);
      symbol_ = 0L;
      onChanged();
      return this;
    }

    private int displaySize_ ;
    /**
     * <code>sint32 displaySize = 8;</code>
     * @return Whether the displaySize field is set.
     */
    @java.lang.Override
    public boolean hasDisplaySize() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>sint32 displaySize = 8;</code>
     * @return The displaySize.
     */
    @java.lang.Override
    public int getDisplaySize() {
      return displaySize_;
    }
    /**
     * <code>sint32 displaySize = 8;</code>
     * @param value The displaySize to set.
     * @return This builder for chaining.
     */
    public Builder setDisplaySize(int value) {
      bitField0_ |= 0x00000010;
      displaySize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>sint32 displaySize = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisplaySize() {
      bitField0_ = (bitField0_ & ~0x00000010);
      displaySize_ = 0;
      onChanged();
      return this;
    }

    private boolean imported_ ;
    /**
     * <code>bool imported = 9;</code>
     * @return Whether the imported field is set.
     */
    @java.lang.Override
    public boolean hasImported() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>bool imported = 9;</code>
     * @return The imported.
     */
    @java.lang.Override
    public boolean getImported() {
      return imported_;
    }
    /**
     * <code>bool imported = 9;</code>
     * @param value The imported to set.
     * @return This builder for chaining.
     */
    public Builder setImported(boolean value) {
      bitField0_ |= 0x00000020;
      imported_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool imported = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearImported() {
      bitField0_ = (bitField0_ & ~0x00000020);
      imported_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WISE.GridProto.CwfgmTarget)
  }

  // @@protoc_insertion_point(class_scope:WISE.GridProto.CwfgmTarget)
  private static final ca.wise.grid.proto.CwfgmTarget DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.wise.grid.proto.CwfgmTarget();
  }

  public static ca.wise.grid.proto.CwfgmTarget getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CwfgmTarget>
      PARSER = new com.google.protobuf.AbstractParser<CwfgmTarget>() {
    @java.lang.Override
    public CwfgmTarget parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CwfgmTarget(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CwfgmTarget> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CwfgmTarget> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.wise.grid.proto.CwfgmTarget getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

