// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wcsData.proto

package ca.wise.grid.proto;

/**
 * Protobuf type {@code WISE.GridProto.wcsData}
 */
public final class wcsData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WISE.GridProto.wcsData)
    wcsDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use wcsData.newBuilder() to construct.
  private wcsData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private wcsData() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new wcsData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private wcsData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            version_ = input.readInt32();
            break;
          }
          case 18: {
            ca.wise.grid.proto.wcsData.locationFile.Builder subBuilder = null;
            if (dataCase_ == 2) {
              subBuilder = ((ca.wise.grid.proto.wcsData.locationFile) data_).toBuilder();
            }
            data_ =
                input.readMessage(ca.wise.grid.proto.wcsData.locationFile.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ca.wise.grid.proto.wcsData.locationFile) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 2;
            break;
          }
          case 32: {

            xSize_ = input.readUInt32();
            break;
          }
          case 40: {

            ySize_ = input.readUInt32();
            break;
          }
          case 50: {
            ca.wise.grid.proto.wcsData.binaryData.Builder subBuilder = null;
            if (binary_ != null) {
              subBuilder = binary_.toBuilder();
            }
            binary_ = input.readMessage(ca.wise.grid.proto.wcsData.binaryData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(binary_);
              binary_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.wise.grid.proto.wcsDataPackage.internal_static_WISE_GridProto_wcsData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.wise.grid.proto.wcsDataPackage.internal_static_WISE_GridProto_wcsData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.wise.grid.proto.wcsData.class, ca.wise.grid.proto.wcsData.Builder.class);
  }

  public interface locationFileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WISE.GridProto.wcsData.locationFile)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    int getVersion();

    /**
     * <code>string filename = 2;</code>
     * @return The filename.
     */
    java.lang.String getFilename();
    /**
     * <code>string filename = 2;</code>
     * @return The bytes for filename.
     */
    com.google.protobuf.ByteString
        getFilenameBytes();

    /**
     * <code>.google.protobuf.StringValue projectionFilename = 3;</code>
     * @return Whether the projectionFilename field is set.
     */
    boolean hasProjectionFilename();
    /**
     * <code>.google.protobuf.StringValue projectionFilename = 3;</code>
     * @return The projectionFilename.
     */
    com.google.protobuf.StringValue getProjectionFilename();
    /**
     * <code>.google.protobuf.StringValue projectionFilename = 3;</code>
     */
    com.google.protobuf.StringValueOrBuilder getProjectionFilenameOrBuilder();
  }
  /**
   * Protobuf type {@code WISE.GridProto.wcsData.locationFile}
   */
  public static final class locationFile extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:WISE.GridProto.wcsData.locationFile)
      locationFileOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use locationFile.newBuilder() to construct.
    private locationFile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private locationFile() {
      filename_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new locationFile();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private locationFile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              version_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              filename_ = s;
              break;
            }
            case 26: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (projectionFilename_ != null) {
                subBuilder = projectionFilename_.toBuilder();
              }
              projectionFilename_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(projectionFilename_);
                projectionFilename_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.grid.proto.wcsDataPackage.internal_static_WISE_GridProto_wcsData_locationFile_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.grid.proto.wcsDataPackage.internal_static_WISE_GridProto_wcsData_locationFile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.grid.proto.wcsData.locationFile.class, ca.wise.grid.proto.wcsData.locationFile.Builder.class);
    }

    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }

    public static final int FILENAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object filename_;
    /**
     * <code>string filename = 2;</code>
     * @return The filename.
     */
    @java.lang.Override
    public java.lang.String getFilename() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filename_ = s;
        return s;
      }
    }
    /**
     * <code>string filename = 2;</code>
     * @return The bytes for filename.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROJECTIONFILENAME_FIELD_NUMBER = 3;
    private com.google.protobuf.StringValue projectionFilename_;
    /**
     * <code>.google.protobuf.StringValue projectionFilename = 3;</code>
     * @return Whether the projectionFilename field is set.
     */
    @java.lang.Override
    public boolean hasProjectionFilename() {
      return projectionFilename_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue projectionFilename = 3;</code>
     * @return The projectionFilename.
     */
    @java.lang.Override
    public com.google.protobuf.StringValue getProjectionFilename() {
      return projectionFilename_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : projectionFilename_;
    }
    /**
     * <code>.google.protobuf.StringValue projectionFilename = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StringValueOrBuilder getProjectionFilenameOrBuilder() {
      return getProjectionFilename();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (version_ != 0) {
        output.writeInt32(1, version_);
      }
      if (!getFilenameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, filename_);
      }
      if (projectionFilename_ != null) {
        output.writeMessage(3, getProjectionFilename());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (!getFilenameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, filename_);
      }
      if (projectionFilename_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getProjectionFilename());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ca.wise.grid.proto.wcsData.locationFile)) {
        return super.equals(obj);
      }
      ca.wise.grid.proto.wcsData.locationFile other = (ca.wise.grid.proto.wcsData.locationFile) obj;

      if (getVersion()
          != other.getVersion()) return false;
      if (!getFilename()
          .equals(other.getFilename())) return false;
      if (hasProjectionFilename() != other.hasProjectionFilename()) return false;
      if (hasProjectionFilename()) {
        if (!getProjectionFilename()
            .equals(other.getProjectionFilename())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + FILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getFilename().hashCode();
      if (hasProjectionFilename()) {
        hash = (37 * hash) + PROJECTIONFILENAME_FIELD_NUMBER;
        hash = (53 * hash) + getProjectionFilename().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ca.wise.grid.proto.wcsData.locationFile parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.grid.proto.wcsData.locationFile parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.grid.proto.wcsData.locationFile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.grid.proto.wcsData.locationFile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.grid.proto.wcsData.locationFile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.grid.proto.wcsData.locationFile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.grid.proto.wcsData.locationFile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.wise.grid.proto.wcsData.locationFile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.wise.grid.proto.wcsData.locationFile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ca.wise.grid.proto.wcsData.locationFile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.wise.grid.proto.wcsData.locationFile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.wise.grid.proto.wcsData.locationFile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ca.wise.grid.proto.wcsData.locationFile prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WISE.GridProto.wcsData.locationFile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WISE.GridProto.wcsData.locationFile)
        ca.wise.grid.proto.wcsData.locationFileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.wise.grid.proto.wcsDataPackage.internal_static_WISE_GridProto_wcsData_locationFile_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.wise.grid.proto.wcsDataPackage.internal_static_WISE_GridProto_wcsData_locationFile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ca.wise.grid.proto.wcsData.locationFile.class, ca.wise.grid.proto.wcsData.locationFile.Builder.class);
      }

      // Construct using ca.wise.grid.proto.wcsData.locationFile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        version_ = 0;

        filename_ = "";

        if (projectionFilenameBuilder_ == null) {
          projectionFilename_ = null;
        } else {
          projectionFilename_ = null;
          projectionFilenameBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.wise.grid.proto.wcsDataPackage.internal_static_WISE_GridProto_wcsData_locationFile_descriptor;
      }

      @java.lang.Override
      public ca.wise.grid.proto.wcsData.locationFile getDefaultInstanceForType() {
        return ca.wise.grid.proto.wcsData.locationFile.getDefaultInstance();
      }

      @java.lang.Override
      public ca.wise.grid.proto.wcsData.locationFile build() {
        ca.wise.grid.proto.wcsData.locationFile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ca.wise.grid.proto.wcsData.locationFile buildPartial() {
        ca.wise.grid.proto.wcsData.locationFile result = new ca.wise.grid.proto.wcsData.locationFile(this);
        result.version_ = version_;
        result.filename_ = filename_;
        if (projectionFilenameBuilder_ == null) {
          result.projectionFilename_ = projectionFilename_;
        } else {
          result.projectionFilename_ = projectionFilenameBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.wise.grid.proto.wcsData.locationFile) {
          return mergeFrom((ca.wise.grid.proto.wcsData.locationFile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ca.wise.grid.proto.wcsData.locationFile other) {
        if (other == ca.wise.grid.proto.wcsData.locationFile.getDefaultInstance()) return this;
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (!other.getFilename().isEmpty()) {
          filename_ = other.filename_;
          onChanged();
        }
        if (other.hasProjectionFilename()) {
          mergeProjectionFilename(other.getProjectionFilename());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ca.wise.grid.proto.wcsData.locationFile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ca.wise.grid.proto.wcsData.locationFile) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int version_ ;
      /**
       * <code>int32 version = 1;</code>
       * @return The version.
       */
      @java.lang.Override
      public int getVersion() {
        return version_;
      }
      /**
       * <code>int32 version = 1;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object filename_ = "";
      /**
       * <code>string filename = 2;</code>
       * @return The filename.
       */
      public java.lang.String getFilename() {
        java.lang.Object ref = filename_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          filename_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string filename = 2;</code>
       * @return The bytes for filename.
       */
      public com.google.protobuf.ByteString
          getFilenameBytes() {
        java.lang.Object ref = filename_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filename_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string filename = 2;</code>
       * @param value The filename to set.
       * @return This builder for chaining.
       */
      public Builder setFilename(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        filename_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string filename = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFilename() {
        
        filename_ = getDefaultInstance().getFilename();
        onChanged();
        return this;
      }
      /**
       * <code>string filename = 2;</code>
       * @param value The bytes for filename to set.
       * @return This builder for chaining.
       */
      public Builder setFilenameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        filename_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.StringValue projectionFilename_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> projectionFilenameBuilder_;
      /**
       * <code>.google.protobuf.StringValue projectionFilename = 3;</code>
       * @return Whether the projectionFilename field is set.
       */
      public boolean hasProjectionFilename() {
        return projectionFilenameBuilder_ != null || projectionFilename_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue projectionFilename = 3;</code>
       * @return The projectionFilename.
       */
      public com.google.protobuf.StringValue getProjectionFilename() {
        if (projectionFilenameBuilder_ == null) {
          return projectionFilename_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : projectionFilename_;
        } else {
          return projectionFilenameBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue projectionFilename = 3;</code>
       */
      public Builder setProjectionFilename(com.google.protobuf.StringValue value) {
        if (projectionFilenameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          projectionFilename_ = value;
          onChanged();
        } else {
          projectionFilenameBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue projectionFilename = 3;</code>
       */
      public Builder setProjectionFilename(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (projectionFilenameBuilder_ == null) {
          projectionFilename_ = builderForValue.build();
          onChanged();
        } else {
          projectionFilenameBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue projectionFilename = 3;</code>
       */
      public Builder mergeProjectionFilename(com.google.protobuf.StringValue value) {
        if (projectionFilenameBuilder_ == null) {
          if (projectionFilename_ != null) {
            projectionFilename_ =
              com.google.protobuf.StringValue.newBuilder(projectionFilename_).mergeFrom(value).buildPartial();
          } else {
            projectionFilename_ = value;
          }
          onChanged();
        } else {
          projectionFilenameBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue projectionFilename = 3;</code>
       */
      public Builder clearProjectionFilename() {
        if (projectionFilenameBuilder_ == null) {
          projectionFilename_ = null;
          onChanged();
        } else {
          projectionFilename_ = null;
          projectionFilenameBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue projectionFilename = 3;</code>
       */
      public com.google.protobuf.StringValue.Builder getProjectionFilenameBuilder() {
        
        onChanged();
        return getProjectionFilenameFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue projectionFilename = 3;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getProjectionFilenameOrBuilder() {
        if (projectionFilenameBuilder_ != null) {
          return projectionFilenameBuilder_.getMessageOrBuilder();
        } else {
          return projectionFilename_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : projectionFilename_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue projectionFilename = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getProjectionFilenameFieldBuilder() {
        if (projectionFilenameBuilder_ == null) {
          projectionFilenameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getProjectionFilename(),
                  getParentForChildren(),
                  isClean());
          projectionFilename_ = null;
        }
        return projectionFilenameBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:WISE.GridProto.wcsData.locationFile)
    }

    // @@protoc_insertion_point(class_scope:WISE.GridProto.wcsData.locationFile)
    private static final ca.wise.grid.proto.wcsData.locationFile DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ca.wise.grid.proto.wcsData.locationFile();
    }

    public static ca.wise.grid.proto.wcsData.locationFile getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<locationFile>
        PARSER = new com.google.protobuf.AbstractParser<locationFile>() {
      @java.lang.Override
      public locationFile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new locationFile(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<locationFile> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<locationFile> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ca.wise.grid.proto.wcsData.locationFile getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface binaryDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WISE.GridProto.wcsData.binaryData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes data = 1;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>bytes dataValid = 2;</code>
     * @return The dataValid.
     */
    com.google.protobuf.ByteString getDataValid();

    /**
     * <code>.google.protobuf.BoolValue isZipped = 3;</code>
     * @return Whether the isZipped field is set.
     */
    boolean hasIsZipped();
    /**
     * <code>.google.protobuf.BoolValue isZipped = 3;</code>
     * @return The isZipped.
     */
    com.google.protobuf.BoolValue getIsZipped();
    /**
     * <code>.google.protobuf.BoolValue isZipped = 3;</code>
     */
    com.google.protobuf.BoolValueOrBuilder getIsZippedOrBuilder();
  }
  /**
   * Protobuf type {@code WISE.GridProto.wcsData.binaryData}
   */
  public static final class binaryData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:WISE.GridProto.wcsData.binaryData)
      binaryDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use binaryData.newBuilder() to construct.
    private binaryData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private binaryData() {
      data_ = com.google.protobuf.ByteString.EMPTY;
      dataValid_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new binaryData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private binaryData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              data_ = input.readBytes();
              break;
            }
            case 18: {

              dataValid_ = input.readBytes();
              break;
            }
            case 26: {
              com.google.protobuf.BoolValue.Builder subBuilder = null;
              if (isZipped_ != null) {
                subBuilder = isZipped_.toBuilder();
              }
              isZipped_ = input.readMessage(com.google.protobuf.BoolValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(isZipped_);
                isZipped_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.grid.proto.wcsDataPackage.internal_static_WISE_GridProto_wcsData_binaryData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.grid.proto.wcsDataPackage.internal_static_WISE_GridProto_wcsData_binaryData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.grid.proto.wcsData.binaryData.class, ca.wise.grid.proto.wcsData.binaryData.Builder.class);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 1;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int DATAVALID_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString dataValid_;
    /**
     * <code>bytes dataValid = 2;</code>
     * @return The dataValid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getDataValid() {
      return dataValid_;
    }

    public static final int ISZIPPED_FIELD_NUMBER = 3;
    private com.google.protobuf.BoolValue isZipped_;
    /**
     * <code>.google.protobuf.BoolValue isZipped = 3;</code>
     * @return Whether the isZipped field is set.
     */
    @java.lang.Override
    public boolean hasIsZipped() {
      return isZipped_ != null;
    }
    /**
     * <code>.google.protobuf.BoolValue isZipped = 3;</code>
     * @return The isZipped.
     */
    @java.lang.Override
    public com.google.protobuf.BoolValue getIsZipped() {
      return isZipped_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : isZipped_;
    }
    /**
     * <code>.google.protobuf.BoolValue isZipped = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.BoolValueOrBuilder getIsZippedOrBuilder() {
      return getIsZipped();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!data_.isEmpty()) {
        output.writeBytes(1, data_);
      }
      if (!dataValid_.isEmpty()) {
        output.writeBytes(2, dataValid_);
      }
      if (isZipped_ != null) {
        output.writeMessage(3, getIsZipped());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, data_);
      }
      if (!dataValid_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, dataValid_);
      }
      if (isZipped_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getIsZipped());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ca.wise.grid.proto.wcsData.binaryData)) {
        return super.equals(obj);
      }
      ca.wise.grid.proto.wcsData.binaryData other = (ca.wise.grid.proto.wcsData.binaryData) obj;

      if (!getData()
          .equals(other.getData())) return false;
      if (!getDataValid()
          .equals(other.getDataValid())) return false;
      if (hasIsZipped() != other.hasIsZipped()) return false;
      if (hasIsZipped()) {
        if (!getIsZipped()
            .equals(other.getIsZipped())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + DATAVALID_FIELD_NUMBER;
      hash = (53 * hash) + getDataValid().hashCode();
      if (hasIsZipped()) {
        hash = (37 * hash) + ISZIPPED_FIELD_NUMBER;
        hash = (53 * hash) + getIsZipped().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ca.wise.grid.proto.wcsData.binaryData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.grid.proto.wcsData.binaryData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.grid.proto.wcsData.binaryData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.grid.proto.wcsData.binaryData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.grid.proto.wcsData.binaryData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.grid.proto.wcsData.binaryData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.grid.proto.wcsData.binaryData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.wise.grid.proto.wcsData.binaryData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.wise.grid.proto.wcsData.binaryData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ca.wise.grid.proto.wcsData.binaryData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.wise.grid.proto.wcsData.binaryData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.wise.grid.proto.wcsData.binaryData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ca.wise.grid.proto.wcsData.binaryData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WISE.GridProto.wcsData.binaryData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WISE.GridProto.wcsData.binaryData)
        ca.wise.grid.proto.wcsData.binaryDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.wise.grid.proto.wcsDataPackage.internal_static_WISE_GridProto_wcsData_binaryData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.wise.grid.proto.wcsDataPackage.internal_static_WISE_GridProto_wcsData_binaryData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ca.wise.grid.proto.wcsData.binaryData.class, ca.wise.grid.proto.wcsData.binaryData.Builder.class);
      }

      // Construct using ca.wise.grid.proto.wcsData.binaryData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        data_ = com.google.protobuf.ByteString.EMPTY;

        dataValid_ = com.google.protobuf.ByteString.EMPTY;

        if (isZippedBuilder_ == null) {
          isZipped_ = null;
        } else {
          isZipped_ = null;
          isZippedBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.wise.grid.proto.wcsDataPackage.internal_static_WISE_GridProto_wcsData_binaryData_descriptor;
      }

      @java.lang.Override
      public ca.wise.grid.proto.wcsData.binaryData getDefaultInstanceForType() {
        return ca.wise.grid.proto.wcsData.binaryData.getDefaultInstance();
      }

      @java.lang.Override
      public ca.wise.grid.proto.wcsData.binaryData build() {
        ca.wise.grid.proto.wcsData.binaryData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ca.wise.grid.proto.wcsData.binaryData buildPartial() {
        ca.wise.grid.proto.wcsData.binaryData result = new ca.wise.grid.proto.wcsData.binaryData(this);
        result.data_ = data_;
        result.dataValid_ = dataValid_;
        if (isZippedBuilder_ == null) {
          result.isZipped_ = isZipped_;
        } else {
          result.isZipped_ = isZippedBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.wise.grid.proto.wcsData.binaryData) {
          return mergeFrom((ca.wise.grid.proto.wcsData.binaryData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ca.wise.grid.proto.wcsData.binaryData other) {
        if (other == ca.wise.grid.proto.wcsData.binaryData.getDefaultInstance()) return this;
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (other.getDataValid() != com.google.protobuf.ByteString.EMPTY) {
          setDataValid(other.getDataValid());
        }
        if (other.hasIsZipped()) {
          mergeIsZipped(other.getIsZipped());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ca.wise.grid.proto.wcsData.binaryData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ca.wise.grid.proto.wcsData.binaryData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 1;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 1;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString dataValid_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes dataValid = 2;</code>
       * @return The dataValid.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getDataValid() {
        return dataValid_;
      }
      /**
       * <code>bytes dataValid = 2;</code>
       * @param value The dataValid to set.
       * @return This builder for chaining.
       */
      public Builder setDataValid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dataValid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes dataValid = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataValid() {
        
        dataValid_ = getDefaultInstance().getDataValid();
        onChanged();
        return this;
      }

      private com.google.protobuf.BoolValue isZipped_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> isZippedBuilder_;
      /**
       * <code>.google.protobuf.BoolValue isZipped = 3;</code>
       * @return Whether the isZipped field is set.
       */
      public boolean hasIsZipped() {
        return isZippedBuilder_ != null || isZipped_ != null;
      }
      /**
       * <code>.google.protobuf.BoolValue isZipped = 3;</code>
       * @return The isZipped.
       */
      public com.google.protobuf.BoolValue getIsZipped() {
        if (isZippedBuilder_ == null) {
          return isZipped_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : isZipped_;
        } else {
          return isZippedBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.BoolValue isZipped = 3;</code>
       */
      public Builder setIsZipped(com.google.protobuf.BoolValue value) {
        if (isZippedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          isZipped_ = value;
          onChanged();
        } else {
          isZippedBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BoolValue isZipped = 3;</code>
       */
      public Builder setIsZipped(
          com.google.protobuf.BoolValue.Builder builderForValue) {
        if (isZippedBuilder_ == null) {
          isZipped_ = builderForValue.build();
          onChanged();
        } else {
          isZippedBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BoolValue isZipped = 3;</code>
       */
      public Builder mergeIsZipped(com.google.protobuf.BoolValue value) {
        if (isZippedBuilder_ == null) {
          if (isZipped_ != null) {
            isZipped_ =
              com.google.protobuf.BoolValue.newBuilder(isZipped_).mergeFrom(value).buildPartial();
          } else {
            isZipped_ = value;
          }
          onChanged();
        } else {
          isZippedBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BoolValue isZipped = 3;</code>
       */
      public Builder clearIsZipped() {
        if (isZippedBuilder_ == null) {
          isZipped_ = null;
          onChanged();
        } else {
          isZipped_ = null;
          isZippedBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BoolValue isZipped = 3;</code>
       */
      public com.google.protobuf.BoolValue.Builder getIsZippedBuilder() {
        
        onChanged();
        return getIsZippedFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.BoolValue isZipped = 3;</code>
       */
      public com.google.protobuf.BoolValueOrBuilder getIsZippedOrBuilder() {
        if (isZippedBuilder_ != null) {
          return isZippedBuilder_.getMessageOrBuilder();
        } else {
          return isZipped_ == null ?
              com.google.protobuf.BoolValue.getDefaultInstance() : isZipped_;
        }
      }
      /**
       * <code>.google.protobuf.BoolValue isZipped = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> 
          getIsZippedFieldBuilder() {
        if (isZippedBuilder_ == null) {
          isZippedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder>(
                  getIsZipped(),
                  getParentForChildren(),
                  isClean());
          isZipped_ = null;
        }
        return isZippedBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:WISE.GridProto.wcsData.binaryData)
    }

    // @@protoc_insertion_point(class_scope:WISE.GridProto.wcsData.binaryData)
    private static final ca.wise.grid.proto.wcsData.binaryData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ca.wise.grid.proto.wcsData.binaryData();
    }

    public static ca.wise.grid.proto.wcsData.binaryData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<binaryData>
        PARSER = new com.google.protobuf.AbstractParser<binaryData>() {
      @java.lang.Override
      public binaryData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new binaryData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<binaryData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<binaryData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ca.wise.grid.proto.wcsData.binaryData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int dataCase_ = 0;
  private java.lang.Object data_;
  public enum DataCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    FILE(2),
    DATA_NOT_SET(0);
    private final int value;
    private DataCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataCase valueOf(int value) {
      return forNumber(value);
    }

    public static DataCase forNumber(int value) {
      switch (value) {
        case 2: return FILE;
        case 0: return DATA_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public DataCase
  getDataCase() {
    return DataCase.forNumber(
        dataCase_);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int FILE_FIELD_NUMBER = 2;
  /**
   * <code>.WISE.GridProto.wcsData.locationFile file = 2;</code>
   * @return Whether the file field is set.
   */
  @java.lang.Override
  public boolean hasFile() {
    return dataCase_ == 2;
  }
  /**
   * <code>.WISE.GridProto.wcsData.locationFile file = 2;</code>
   * @return The file.
   */
  @java.lang.Override
  public ca.wise.grid.proto.wcsData.locationFile getFile() {
    if (dataCase_ == 2) {
       return (ca.wise.grid.proto.wcsData.locationFile) data_;
    }
    return ca.wise.grid.proto.wcsData.locationFile.getDefaultInstance();
  }
  /**
   * <code>.WISE.GridProto.wcsData.locationFile file = 2;</code>
   */
  @java.lang.Override
  public ca.wise.grid.proto.wcsData.locationFileOrBuilder getFileOrBuilder() {
    if (dataCase_ == 2) {
       return (ca.wise.grid.proto.wcsData.locationFile) data_;
    }
    return ca.wise.grid.proto.wcsData.locationFile.getDefaultInstance();
  }

  public static final int XSIZE_FIELD_NUMBER = 4;
  private int xSize_;
  /**
   * <code>uint32 xSize = 4;</code>
   * @return The xSize.
   */
  @java.lang.Override
  public int getXSize() {
    return xSize_;
  }

  public static final int YSIZE_FIELD_NUMBER = 5;
  private int ySize_;
  /**
   * <code>uint32 ySize = 5;</code>
   * @return The ySize.
   */
  @java.lang.Override
  public int getYSize() {
    return ySize_;
  }

  public static final int BINARY_FIELD_NUMBER = 6;
  private ca.wise.grid.proto.wcsData.binaryData binary_;
  /**
   * <code>.WISE.GridProto.wcsData.binaryData binary = 6;</code>
   * @return Whether the binary field is set.
   */
  @java.lang.Override
  public boolean hasBinary() {
    return binary_ != null;
  }
  /**
   * <code>.WISE.GridProto.wcsData.binaryData binary = 6;</code>
   * @return The binary.
   */
  @java.lang.Override
  public ca.wise.grid.proto.wcsData.binaryData getBinary() {
    return binary_ == null ? ca.wise.grid.proto.wcsData.binaryData.getDefaultInstance() : binary_;
  }
  /**
   * <code>.WISE.GridProto.wcsData.binaryData binary = 6;</code>
   */
  @java.lang.Override
  public ca.wise.grid.proto.wcsData.binaryDataOrBuilder getBinaryOrBuilder() {
    return getBinary();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0) {
      output.writeInt32(1, version_);
    }
    if (dataCase_ == 2) {
      output.writeMessage(2, (ca.wise.grid.proto.wcsData.locationFile) data_);
    }
    if (xSize_ != 0) {
      output.writeUInt32(4, xSize_);
    }
    if (ySize_ != 0) {
      output.writeUInt32(5, ySize_);
    }
    if (binary_ != null) {
      output.writeMessage(6, getBinary());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, version_);
    }
    if (dataCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (ca.wise.grid.proto.wcsData.locationFile) data_);
    }
    if (xSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, xSize_);
    }
    if (ySize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, ySize_);
    }
    if (binary_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getBinary());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.wise.grid.proto.wcsData)) {
      return super.equals(obj);
    }
    ca.wise.grid.proto.wcsData other = (ca.wise.grid.proto.wcsData) obj;

    if (getVersion()
        != other.getVersion()) return false;
    if (getXSize()
        != other.getXSize()) return false;
    if (getYSize()
        != other.getYSize()) return false;
    if (hasBinary() != other.hasBinary()) return false;
    if (hasBinary()) {
      if (!getBinary()
          .equals(other.getBinary())) return false;
    }
    if (!getDataCase().equals(other.getDataCase())) return false;
    switch (dataCase_) {
      case 2:
        if (!getFile()
            .equals(other.getFile())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    hash = (37 * hash) + XSIZE_FIELD_NUMBER;
    hash = (53 * hash) + getXSize();
    hash = (37 * hash) + YSIZE_FIELD_NUMBER;
    hash = (53 * hash) + getYSize();
    if (hasBinary()) {
      hash = (37 * hash) + BINARY_FIELD_NUMBER;
      hash = (53 * hash) + getBinary().hashCode();
    }
    switch (dataCase_) {
      case 2:
        hash = (37 * hash) + FILE_FIELD_NUMBER;
        hash = (53 * hash) + getFile().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.wise.grid.proto.wcsData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.grid.proto.wcsData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.grid.proto.wcsData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.grid.proto.wcsData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.grid.proto.wcsData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.grid.proto.wcsData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.grid.proto.wcsData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.grid.proto.wcsData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.grid.proto.wcsData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.wise.grid.proto.wcsData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.grid.proto.wcsData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.grid.proto.wcsData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.wise.grid.proto.wcsData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WISE.GridProto.wcsData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WISE.GridProto.wcsData)
      ca.wise.grid.proto.wcsDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.grid.proto.wcsDataPackage.internal_static_WISE_GridProto_wcsData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.grid.proto.wcsDataPackage.internal_static_WISE_GridProto_wcsData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.grid.proto.wcsData.class, ca.wise.grid.proto.wcsData.Builder.class);
    }

    // Construct using ca.wise.grid.proto.wcsData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = 0;

      xSize_ = 0;

      ySize_ = 0;

      if (binaryBuilder_ == null) {
        binary_ = null;
      } else {
        binary_ = null;
        binaryBuilder_ = null;
      }
      dataCase_ = 0;
      data_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.wise.grid.proto.wcsDataPackage.internal_static_WISE_GridProto_wcsData_descriptor;
    }

    @java.lang.Override
    public ca.wise.grid.proto.wcsData getDefaultInstanceForType() {
      return ca.wise.grid.proto.wcsData.getDefaultInstance();
    }

    @java.lang.Override
    public ca.wise.grid.proto.wcsData build() {
      ca.wise.grid.proto.wcsData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.wise.grid.proto.wcsData buildPartial() {
      ca.wise.grid.proto.wcsData result = new ca.wise.grid.proto.wcsData(this);
      result.version_ = version_;
      if (dataCase_ == 2) {
        if (fileBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = fileBuilder_.build();
        }
      }
      result.xSize_ = xSize_;
      result.ySize_ = ySize_;
      if (binaryBuilder_ == null) {
        result.binary_ = binary_;
      } else {
        result.binary_ = binaryBuilder_.build();
      }
      result.dataCase_ = dataCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.wise.grid.proto.wcsData) {
        return mergeFrom((ca.wise.grid.proto.wcsData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.wise.grid.proto.wcsData other) {
      if (other == ca.wise.grid.proto.wcsData.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (other.getXSize() != 0) {
        setXSize(other.getXSize());
      }
      if (other.getYSize() != 0) {
        setYSize(other.getYSize());
      }
      if (other.hasBinary()) {
        mergeBinary(other.getBinary());
      }
      switch (other.getDataCase()) {
        case FILE: {
          mergeFile(other.getFile());
          break;
        }
        case DATA_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.wise.grid.proto.wcsData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.wise.grid.proto.wcsData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int dataCase_ = 0;
    private java.lang.Object data_;
    public DataCase
        getDataCase() {
      return DataCase.forNumber(
          dataCase_);
    }

    public Builder clearData() {
      dataCase_ = 0;
      data_ = null;
      onChanged();
      return this;
    }


    private int version_ ;
    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <code>int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.grid.proto.wcsData.locationFile, ca.wise.grid.proto.wcsData.locationFile.Builder, ca.wise.grid.proto.wcsData.locationFileOrBuilder> fileBuilder_;
    /**
     * <code>.WISE.GridProto.wcsData.locationFile file = 2;</code>
     * @return Whether the file field is set.
     */
    @java.lang.Override
    public boolean hasFile() {
      return dataCase_ == 2;
    }
    /**
     * <code>.WISE.GridProto.wcsData.locationFile file = 2;</code>
     * @return The file.
     */
    @java.lang.Override
    public ca.wise.grid.proto.wcsData.locationFile getFile() {
      if (fileBuilder_ == null) {
        if (dataCase_ == 2) {
          return (ca.wise.grid.proto.wcsData.locationFile) data_;
        }
        return ca.wise.grid.proto.wcsData.locationFile.getDefaultInstance();
      } else {
        if (dataCase_ == 2) {
          return fileBuilder_.getMessage();
        }
        return ca.wise.grid.proto.wcsData.locationFile.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.GridProto.wcsData.locationFile file = 2;</code>
     */
    public Builder setFile(ca.wise.grid.proto.wcsData.locationFile value) {
      if (fileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        fileBuilder_.setMessage(value);
      }
      dataCase_ = 2;
      return this;
    }
    /**
     * <code>.WISE.GridProto.wcsData.locationFile file = 2;</code>
     */
    public Builder setFile(
        ca.wise.grid.proto.wcsData.locationFile.Builder builderForValue) {
      if (fileBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        fileBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 2;
      return this;
    }
    /**
     * <code>.WISE.GridProto.wcsData.locationFile file = 2;</code>
     */
    public Builder mergeFile(ca.wise.grid.proto.wcsData.locationFile value) {
      if (fileBuilder_ == null) {
        if (dataCase_ == 2 &&
            data_ != ca.wise.grid.proto.wcsData.locationFile.getDefaultInstance()) {
          data_ = ca.wise.grid.proto.wcsData.locationFile.newBuilder((ca.wise.grid.proto.wcsData.locationFile) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 2) {
          fileBuilder_.mergeFrom(value);
        }
        fileBuilder_.setMessage(value);
      }
      dataCase_ = 2;
      return this;
    }
    /**
     * <code>.WISE.GridProto.wcsData.locationFile file = 2;</code>
     */
    public Builder clearFile() {
      if (fileBuilder_ == null) {
        if (dataCase_ == 2) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 2) {
          dataCase_ = 0;
          data_ = null;
        }
        fileBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.WISE.GridProto.wcsData.locationFile file = 2;</code>
     */
    public ca.wise.grid.proto.wcsData.locationFile.Builder getFileBuilder() {
      return getFileFieldBuilder().getBuilder();
    }
    /**
     * <code>.WISE.GridProto.wcsData.locationFile file = 2;</code>
     */
    @java.lang.Override
    public ca.wise.grid.proto.wcsData.locationFileOrBuilder getFileOrBuilder() {
      if ((dataCase_ == 2) && (fileBuilder_ != null)) {
        return fileBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 2) {
          return (ca.wise.grid.proto.wcsData.locationFile) data_;
        }
        return ca.wise.grid.proto.wcsData.locationFile.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.GridProto.wcsData.locationFile file = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.grid.proto.wcsData.locationFile, ca.wise.grid.proto.wcsData.locationFile.Builder, ca.wise.grid.proto.wcsData.locationFileOrBuilder> 
        getFileFieldBuilder() {
      if (fileBuilder_ == null) {
        if (!(dataCase_ == 2)) {
          data_ = ca.wise.grid.proto.wcsData.locationFile.getDefaultInstance();
        }
        fileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.grid.proto.wcsData.locationFile, ca.wise.grid.proto.wcsData.locationFile.Builder, ca.wise.grid.proto.wcsData.locationFileOrBuilder>(
                (ca.wise.grid.proto.wcsData.locationFile) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 2;
      onChanged();;
      return fileBuilder_;
    }

    private int xSize_ ;
    /**
     * <code>uint32 xSize = 4;</code>
     * @return The xSize.
     */
    @java.lang.Override
    public int getXSize() {
      return xSize_;
    }
    /**
     * <code>uint32 xSize = 4;</code>
     * @param value The xSize to set.
     * @return This builder for chaining.
     */
    public Builder setXSize(int value) {
      
      xSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 xSize = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearXSize() {
      
      xSize_ = 0;
      onChanged();
      return this;
    }

    private int ySize_ ;
    /**
     * <code>uint32 ySize = 5;</code>
     * @return The ySize.
     */
    @java.lang.Override
    public int getYSize() {
      return ySize_;
    }
    /**
     * <code>uint32 ySize = 5;</code>
     * @param value The ySize to set.
     * @return This builder for chaining.
     */
    public Builder setYSize(int value) {
      
      ySize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 ySize = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearYSize() {
      
      ySize_ = 0;
      onChanged();
      return this;
    }

    private ca.wise.grid.proto.wcsData.binaryData binary_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.grid.proto.wcsData.binaryData, ca.wise.grid.proto.wcsData.binaryData.Builder, ca.wise.grid.proto.wcsData.binaryDataOrBuilder> binaryBuilder_;
    /**
     * <code>.WISE.GridProto.wcsData.binaryData binary = 6;</code>
     * @return Whether the binary field is set.
     */
    public boolean hasBinary() {
      return binaryBuilder_ != null || binary_ != null;
    }
    /**
     * <code>.WISE.GridProto.wcsData.binaryData binary = 6;</code>
     * @return The binary.
     */
    public ca.wise.grid.proto.wcsData.binaryData getBinary() {
      if (binaryBuilder_ == null) {
        return binary_ == null ? ca.wise.grid.proto.wcsData.binaryData.getDefaultInstance() : binary_;
      } else {
        return binaryBuilder_.getMessage();
      }
    }
    /**
     * <code>.WISE.GridProto.wcsData.binaryData binary = 6;</code>
     */
    public Builder setBinary(ca.wise.grid.proto.wcsData.binaryData value) {
      if (binaryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        binary_ = value;
        onChanged();
      } else {
        binaryBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.WISE.GridProto.wcsData.binaryData binary = 6;</code>
     */
    public Builder setBinary(
        ca.wise.grid.proto.wcsData.binaryData.Builder builderForValue) {
      if (binaryBuilder_ == null) {
        binary_ = builderForValue.build();
        onChanged();
      } else {
        binaryBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.WISE.GridProto.wcsData.binaryData binary = 6;</code>
     */
    public Builder mergeBinary(ca.wise.grid.proto.wcsData.binaryData value) {
      if (binaryBuilder_ == null) {
        if (binary_ != null) {
          binary_ =
            ca.wise.grid.proto.wcsData.binaryData.newBuilder(binary_).mergeFrom(value).buildPartial();
        } else {
          binary_ = value;
        }
        onChanged();
      } else {
        binaryBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.WISE.GridProto.wcsData.binaryData binary = 6;</code>
     */
    public Builder clearBinary() {
      if (binaryBuilder_ == null) {
        binary_ = null;
        onChanged();
      } else {
        binary_ = null;
        binaryBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.WISE.GridProto.wcsData.binaryData binary = 6;</code>
     */
    public ca.wise.grid.proto.wcsData.binaryData.Builder getBinaryBuilder() {
      
      onChanged();
      return getBinaryFieldBuilder().getBuilder();
    }
    /**
     * <code>.WISE.GridProto.wcsData.binaryData binary = 6;</code>
     */
    public ca.wise.grid.proto.wcsData.binaryDataOrBuilder getBinaryOrBuilder() {
      if (binaryBuilder_ != null) {
        return binaryBuilder_.getMessageOrBuilder();
      } else {
        return binary_ == null ?
            ca.wise.grid.proto.wcsData.binaryData.getDefaultInstance() : binary_;
      }
    }
    /**
     * <code>.WISE.GridProto.wcsData.binaryData binary = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.grid.proto.wcsData.binaryData, ca.wise.grid.proto.wcsData.binaryData.Builder, ca.wise.grid.proto.wcsData.binaryDataOrBuilder> 
        getBinaryFieldBuilder() {
      if (binaryBuilder_ == null) {
        binaryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.grid.proto.wcsData.binaryData, ca.wise.grid.proto.wcsData.binaryData.Builder, ca.wise.grid.proto.wcsData.binaryDataOrBuilder>(
                getBinary(),
                getParentForChildren(),
                isClean());
        binary_ = null;
      }
      return binaryBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WISE.GridProto.wcsData)
  }

  // @@protoc_insertion_point(class_scope:WISE.GridProto.wcsData)
  private static final ca.wise.grid.proto.wcsData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.wise.grid.proto.wcsData();
  }

  public static ca.wise.grid.proto.wcsData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<wcsData>
      PARSER = new com.google.protobuf.AbstractParser<wcsData>() {
    @java.lang.Override
    public wcsData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new wcsData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<wcsData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<wcsData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.wise.grid.proto.wcsData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

