// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wcsData.proto

package ca.wise.grid.proto;

public interface wcsDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.GridProto.wcsData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>.WISE.GridProto.wcsData.locationFile file = 2;</code>
   * @return Whether the file field is set.
   */
  boolean hasFile();
  /**
   * <code>.WISE.GridProto.wcsData.locationFile file = 2;</code>
   * @return The file.
   */
  ca.wise.grid.proto.wcsData.locationFile getFile();
  /**
   * <code>.WISE.GridProto.wcsData.locationFile file = 2;</code>
   */
  ca.wise.grid.proto.wcsData.locationFileOrBuilder getFileOrBuilder();

  /**
   * <code>uint32 xSize = 4;</code>
   * @return The xSize.
   */
  int getXSize();

  /**
   * <code>uint32 ySize = 5;</code>
   * @return The ySize.
   */
  int getYSize();

  /**
   * <code>.WISE.GridProto.wcsData.binaryData binary = 6;</code>
   * @return Whether the binary field is set.
   */
  boolean hasBinary();
  /**
   * <code>.WISE.GridProto.wcsData.binaryData binary = 6;</code>
   * @return The binary.
   */
  ca.wise.grid.proto.wcsData.binaryData getBinary();
  /**
   * <code>.WISE.GridProto.wcsData.binaryData binary = 6;</code>
   */
  ca.wise.grid.proto.wcsData.binaryDataOrBuilder getBinaryOrBuilder();

  public ca.wise.grid.proto.wcsData.DataCase getDataCase();
}
